= Аннотация

В данном разделе приведена документация для модуля {dv} 5. {wincl}.

Документация описывает инструкцию по установке {wincl}а, описание возможностей и примеры работы с модулем. Описание настройки представлений и поисковых запросов приведено в документе xref:engineer:ROOT:annotation.adoc[Руководстве по настройке {dv}].

Документация предназначена для пользователей, администраторов и специалистов системы {dv}.

IMPORTANT: Для работы с модулем {wincl} лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Windows-Client_.

== Как организована документация

.Документация содержит следующие разделы:
* Общие сведения о модуле, требования к подготовке пользователей.
* xref:module-structure.adoc[] -- перечисление составных частей модуля.
* xref:admin:install.adoc[] -- инструкция по установке модуля.
* xref:admin:update.adoc[] -- инструкция по обновлению версии модуля.
* Функции администратора модуля {wincl} -- перечень задача администратора модуля.
* Руководство пользователя модуля {wincl} -- описание пользовательского интерфейса, настроек {wincl}а и варианты использования программы.
* xref:user:Operations_rma.adoc[] -- содержит описание пользовательского интерфейса РМА, предназначенного для выполнения операций специалистом {dv}. Описывает примеры настройки дискреционной модели безопасности, и другие задачи специалиста.
