= Общие сведения о модуле

В данном разделе приведена документация для модуля {wincl}.

Документация описывает инструкцию по установке {wincl}а, описание возможностей и примеры работы с модулем. Описание настройки представлений и поисковых запросов приведено в xref:engineer:ROOT:index.adoc[Руководстве по настройке {dv}].

Документация предназначена для пользователей, администраторов и специалистов системы {dv}.

WARNING: Для работы с модулем {wincl} лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Windows-Client_.

[#arrangement]
== Как организована документация модуля

.Документация содержит следующие разделы:
* Общие сведения о модуле, требования к подготовке пользователей.
* xref:module-structure.adoc[] -- перечисление составных частей модуля.
* xref:admin:install.adoc[] -- инструкция по установке модуля.
* xref:admin:update-module.adoc[] -- инструкция по обновлению версии модуля.
* Функции администратора модуля {wincl} -- перечень задача администратора модуля.
* Руководство пользователя {wincl} -- описание пользовательского интерфейса, настроек {wincl}а и варианты использования программы.
* Описание операций в РМА -- содержит описание пользовательского интерфейса РМА, предназначенного для выполнения операций специалистом {dv}. Описывает примеры настройки дискреционной модели безопасности, и другие задачи специалиста.
