= Структура и функции модуля

.Модуль {wincl} состоит из двух частей:
. Серверная часть, устанавливаемая на компьютер с сервером {dv}, содержит:
.. Библиотеку карточек "WindowsClient". +
Библиотека карточек нужна для регистрации пакета установки "{wincl}а".
+
.. Пакет установки клиентской части модуля _{wincl}_.
. Клиентская часть, устанавливаемая на компьютеры пользователей {dv}, включает две клиентских программы:
.. _{wincl}_.
.. _Рабочее место администратора_.

_{wincl}_ является базовым модулем системы {dv}. Модуль предоставляет клиентские программы для работы с системой {dv} на персональном компьютере с ОС Windows:

. {wincl} -- классическая клиентская программа {dv} для пользователей, администраторов и инженеров {dv}.
. Рабочее место администратора (РМА) -- клиентская программа {dv} для администраторов и инженеров {dv}, выполненная в виде компонента ActiveX, запускаемого из веб-браузера Internet Explorer.
+
[NOTE]
====
Далее, под "{wincl}ом" будет подразумеваться программа _{wincl}_, если отдельно не указано, что речь идет о модуле.
====

.{wincl} предоставляет следующие возможности:
* Авторизация пользователей в системе {dv}.
* Работа с карточками и папками {dv}: создание, копирование и удаление, работа с ярлыками карточек {dv}, изменение свойств (включая свойства безопасности).
* Работа со справочниками и конструкторами {dv}.
* Конвертация карточек в шаблоны карточек.
* Создание, копирование и удаление _папок_ {dv}.
* Отображение данных карточек в формате представлений с возможностью сортировки и фильтрации.
* Поиск карточек с использованием _полнотекстового_ и _атрибутивного поиска_.
* Настройка свойств карточек и папок.
* Экспорт данных из представления в файл `.xls`.
* Расширение функциональных возможностей с помощью устанавливаемых модулей {dv}, а также _расширений_ {wincl}а (библиотек DLL, предоставляющая дополнительную функциональность).
* Локализация, то есть изменение языка пользовательского интерфейса.
* Автоматическая загрузка и установка клиентских компонентов модулей и приложений {dv} в соответствии с правилами установки.

РМА предлагает аналогичные {wincl}у функции, а также возможность настраивать общие для всех пользователей _поисковые запросы_ и представления.

.{wincl} ориентирован на различные группы конечных пользователей:
* Исполнители, выполняющие все операции по работе с документами, начиная от регистрации полученных документов, и заканчивая отправкой документов в архив.
* Руководители среднего звена, использующие систему документооборота для исполнения или выдачи поручений, а также для согласования документов.

{wincl} рассчитан на повседневную работу конечных пользователей, администраторов и инженеров {dv}. РМА рекомендуется использовать для настройки поисковых запросов и представлений, выполнения операций импорта данных из формата `.xml`, а также выполнения других операций, которые недоступны в {wincl}е.
