= Необходимое программное обеспечение

== Операционная система

* Microsoft Windows 7 SP 1 (Enterprise, Professional, Ultimate).
* Microsoft Windows 8/8.1 (Pro, Enterprise)footnote:[Работа в ОС Windows 8 поддерживается только в режиме "Рабочего стола". Работа в режиме Metro, в том числе в Metro-Internet Explorer, не поддерживается.].
* Microsoft Windows 10 (Pro, Enterprise).
* Любая ОС, указанная в xref:5.5.5@platform:ROOT:requirements-software.adoc[требованиях] серверной части модуля {pl}.

== Обязательное программное обеспечение

. Microsoft .NET Framework {net-v1}.
. Microsoft Internet Explorerfootnote:[Требуется для работы в РМА.] версии 8, 9, 10 или 11.
. Microsoft Visual C++ Redistributable последней версии, скачать можно https://aka.ms/vs/17/release/vc_redist.x86.exe[по ссылке].

Следующее программное обеспечение не является обязательным, но его отсутствие может повлиять на функциональные возможности {wincl}а и РМА.

.Дополнительное программное обеспечение
[cols="25%,75%"]
|===
|Веб-браузер для открытия карточек по ссылке
a|* 32-разрядный Microsoft Internet Explorer версии {ie-v}.
* Google Chrome версий {gc-v} с расширением "{dv} Windows Client Launcher".
* Opera версий {op-v}.

|Microsoft Office
a|32-разрядные версии приложений Microsoft Office {office-v}:

. Microsoft Word для синхронизации полей карточки.
. Microsoft Lync 2010 или 2013, или Skype для бизнеса 2016 для отображения статуса сотрудника в карточке.
+
[NOTE]
====
Если установленная на компьютере программа "Microsoft Lync 2013" была обновлена на более раннюю версию (например, "Microsoft Lync 2010"), то для корректной работы функции отображения статуса сотрудника нужно удалить из реестра ветки программы "Microsoft Lync 2013":

* `HKCU\Software\IM Providers\Lync`.
* `HKLM\Software\IM Providers\Lync`.
====
+
. Microsoft Outlook для отправки карточек по электронной почте.
. Microsoft Excel для экспорта представлений.
. Компонент "Общие средства Office".
|===
