= Работа с ярлыками карточек

_Ярлыком карточки_ называется ссылка на карточку, которую пользователь может разместить в любой удобной для него папке. Ярлыки создаются для более удобного обращения к карточке.

.С помощью ярлыка можно осуществить следующие действия:
* Переместить ярлык карточки в любую папку РМА при помощи команды контекстного меню _Переместить ярлык в папку_.
* Переместить группы ярлыков карточек в любую папку РМА при помощи команды контекстного меню _Переместить ярлыки в папку_.
* Скопировать ярлык карточки в любую папку РМА с помощью команды контекстного меню _Скопировать ярлык в папку_. +
При этом все данные карточки дублируются в указанной папке.
+
* Скопировать группы ярлыков карточек в любую папку РМА с помощью команды контекстного меню _Скопировать ярлыки в папку_. +
При этом все данные карточек дублируются в указанной папке.
+
* Удалить ярлыки карточек. Можно удалить как сам ярлык, так и карточку. Для выполнения указанных действий предназначены пункты контекстного меню _Удалить карточку_ и _Удалить ярлык_ соответственно.
* Разместить ярлыки некоторых типов карточек в любой папке РМА. +
Например, в приложении _{dm}_ -- при создании карточки по шаблону или при создании карточки из уже имеющейся карточки.

[NOTE]
====
{bo} {dv} при работе в пользовательских папках создаются как ярлыки. +
Соответствующие им карточки автоматически создаются в системной папке _Карточки_.
====
