= Создание экземпляра по шаблону карточки

По любому шаблону карточки можно создать экземпляр карточки, который будет содержать все данные, имеющиеся в шаблоне (включая заполненные поля, прикрепленные файлы и карточки файлов и т. д.).

Для создания экземпляра карточки по существующему шаблону выполните следующие действия:

. Выберите шаблон, по которому будет создан экземпляр:
* Для создания экземпляра по закрытой карточке шаблона выполните одно из действий:
** Выделите строку шаблона на правой панели _РМА_, после чего выберите из контекстного меню команду *Создать карточку по этому шаблону*.
** Дважды щелкнуть в правой панели _РМА_ по строке шаблона.
* Для создания экземпляра из открытого шаблона карточки следует нажать кнопку *Конвертировать в шаблон*. Очевидно, что это действие возможно, если шаблон содержит такую кнопку.
+
Будет открыто окно *Выбор папки*, предлагающее указать папку для размещения экземпляра карточки, если в настройках шаблона не указана папка по умолчанию. В противном случае будет открыт вновь созданный экземпляр карточки.
. В окне *Выбор папки* выберите из существующих или создайте новую папку, в которой вы хотите разместить экземпляр карточки.
+
[NOTE]
====
Если в настройках шаблона указана папка для создания экземпляра, шаг 2 будет пропущен.
====
. Заполните/отредактируйте поля созданной и выведенной на экран карточки.
. Сохраните изменения и закройте карточку.
