= Копирование ветки дерева папок

Ветку xref:rma/interface.adoc#tree[дерева папок] (пользовательскую папку вместе со всеми дочерними папками всех уровней) можно скопировать в другую папку, не принадлежащую этой ветке.

Ветка дерева копируется с сохранением структуры папок. Все папки копируются вместе с настройками, то есть все свойства скопированных папок сохраняют оригинальные значения. Карточки в скопированных папках заменяются ярлыками карточек.

Если название верхней папки копируемой ветки совпадает с названием уже имеющейся в папке назначения подпапки, копии будет присвоено то же название, но с номером (1). При повторном копировании нумерация будет продолжена.

[NOTE]
====
Производящий копирование ветки дерева папок пользователь должен иметь права на чтение и изменение всех папок этой ветки.
====

.Чтобы скопировать ветку дерева папок:
. Выберите команду контекстного меню _Скопировать структуру папок_.
. Выберите из главного меню последовательно menu:Файл[Папка > Скопировать структуру папок].
