= Копирование и перемещение папок

[#copy]
== Копирование папки в другую папку

Папку можно скопировать в любую другую папку, за исключением собственной дочерней папки. При этом папка со всеми данными дублируется в выбранной папке, а карточки заменяются ярлыками карточек.

include::partial$excerpts.adoc[tags=rename]

Для копирования папки выполните одно из следующих действий:

. Выберите команду контекстного меню *Скопировать папку*.
. Выберите из главного меню последовательно menu:Файл[Папка].

[#move]
== Перемещение папки

Папку можно переместить в любую другую папку, не являющуюся по отношению к ней дочерней.

При этом папка со всеми содержащимися в ней данными удаляется оттуда, где она находилась ранее, и копируется в выбранную папку.

.Чтобы переместить папку, выполните одно из следующих действий:
. Выберите команду контекстного меню _Переместить папку_.
. Выберите из главного меню menu:Файл[Папка > Переместить папку].
. Нажмите на перемещаемую папку и, удерживая левую кнопку мыши нажатой, перетащите её в нужную папку. При использовании этого способа на экран выводится диалог: `Вы уверены, что хотите переместить папку "Такую-то" в папку "Такую-то"?`. В диалоге пользователь может подтвердить или отменить перемещение.
+
[WARNING]
====
Если пользователь установит в окне полученного сообщения флаг `*Не выводить больше это сообщение*`, в дальнейшем сообщение на экран выводиться не будет. Восстановить получение сообщения нельзя.
====
