= Возможности поиска

.РМА предоставляет несколько видов поиска:
Поиск папки::
Осуществляет контекстный поиск папки по ключевой строке, которая может представлять собой сочетание символов, слово или фразу.
+
В результате такого поиска будет выделена первая найденная папка, отвечающая заданному условию.

Поиск по представлению::
Это контекстный поиск карточек в текущем представлении по ключевой строке, которая может представлять собой сочетание символов, слово или фразу.
+
В результате такого поиска будет выделена первая карточка, отвечающая заданному условию, см. подробнее xref:rma/views-search-rma.adoc[Поиск карточки по представлению].

Расширенный поиск::
Выполняется на основе поисковых запросов, которые позволяют осуществлять поиск карточек в соответствии с определёнными критериями.
+
Результаты последнего поиска отображаются в виртуальной папке _Результаты поиска_, которая автоматически создаётся при первом запуске РМА.

Поиск при помощи "Личного помощника"::
Поиск осуществляется на основе запросов, аналогичных запросам для расширенного поиска. Однако поиск выполняется системой самостоятельно через определённые интервалы времени и может производиться как при открытом, так и при закрытом РМА.
+
[NOTE]
====
В результаты поиска попадут только те карточки, к которым пользователю разрешён доступ.
====

Быстрый поиск::
Быстрый поиск значений в полях и таблицах открытых карточек выполняется аналогично в {wincl}е и РМА. См. "xref:search-substring.adoc[Быстрый поиск по подстроке]".
