= Работа с представлениями

_Представлением_ называется таблица, в которой отображается информация о карточках в области представления. Главным достоинством табличного представления данных является то, что оно отображает информацию о карточках различных типов в одной таблице. Таким образом на экран выводятся только необходимые поля и обеспечивается возможность регулировать высоту строк и ширину столбцов в зависимости от текущих потребностей пользователя.

Для любой папки можно выбрать представление, наиболее наглядно отражающее информацию содержащихся в ней карточек и не включающее избыточной информации.

При помощи папки-делегата для любой папки можно выбрать несколько представлений, каждое из которых будет отвечать какой-либо одной из поставленных задач. В папке-делегате отображается то же содержимое, но представление можно выбрать любое.

По умолчанию информация вновь создаваемой папки отображается в виде стандартного представления -- дайджеста, кратко описывающего карточку одной строкой текста. Для каждого типа карточки предусмотрен определённый дайджест.

Таблица представления состоит из колонок и строк. Строки таблицы могут представлять собой карточки, ярлыки карточек, строки секций карточек (например, в представлении по справочникам) и т.п. Колонки таблицы выбираются пользователем в зависимости от назначения представления в окне _Настройка данных представления_ (например, _Автор_, _Дата создания_, _Название_).

== Дайджест и пользовательские представления

Пользователь может оставить представление данных, установленное по умолчанию, выбрать его из уже существующих или определить самостоятельно.

По умолчанию устанавливается универсальное представление карточек -- дайджест, который может использоваться для карточек любого типа.

.Дайджест состоит из четырех колонок:
. _Тип карточки_: Входящий документ, Исходящий документ, Процесс и т. д.
. _Дайджест карточки_: для документа -- название документа и его номер, для файла -- файл и название, для процесса -- название.
. _Создана_: дата создания карточки.
. _Изменена_: дата последнего изменения.

Представления, создаваемые пользователем, должны определяться в соответствии с их назначением и включать все необходимые сведения о карточках (например, для построения отчетов).

[NOTE]
====
Сотрудник сможет работать с пользовательскими представлениями только в том случае, если ему выданы права на чтение данных из карточки сохранённых поисковых запросов.
====

== Настройка представлений

В зависимости от назначения представления, пользователь может изменять порядок строк и колонок таблицы.

* Сортировать карточки в определённом порядке. Например, в алфавитном порядке по названию карточки.
* Группировать карточки по общему признаку.
* Автоматически фильтровать карточки по данным какой-либо колонки, оставляя на экране только нужные.
* Изменять размеры строк и порядок следования колонок таблицы.

Каждый пользователь может xref:rma/folders-contents.adoc#change-view[установить] для любой доступной ему папки удобное представление.

Настройки представления: сортировка, группировка данных представления, порядок и ширина столбцов сохраняются в системе и будут применены при следующем открытии РМА. Однако, данные настройки сохраняются, пока не изменятся авторские настройки представления.

Подробнее о сохранении пользовательских настроек см. xref:rma/folders-contents.adoc#save-cancel[Сохранение и отмена пользовательских настроек].
