[[ariaid-title1]]
== Настройка кэширования данных

Режим клиентского кэширования для всех пользователей настраивается в «Консоли настройки Docsvision» (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Платформа». Руководство администратора_#, пункт «Сервер»).

Если требуется, администратор может переопределить режим кэширования для отдельного пользователя или всех пользователей определенного компьютера.

. [.ph .cmd]#Откройте [.dfn .term]_Редактор реестра_ на компьютере пользователя, для которого нужно установить собственный режим кэширования.#
. [.ph .cmd]#Перейдите к ветке: [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\ObjectManager`.#
* [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Platform\5.5\ObjectManager` – чтобы настроить режим кэширования для всех пользователей компьютера;
* [.ph .filepath]`HKCU\SOFTWARE\DocsVision\Platform\5.5\ObjectManager` – чтобы настроить режим кэширования для текущего пользователя.
+
Если раздел ObjectManager отсутствует, создайте его самостоятельно.
+
Локальная настройка в реестре приоритетнее настройки на сервере. Локальная настройка в ветке [.ph .filepath]`HKCU` приоритетнее, чем настройка в ветке [.ph .filepath]`HKLM`.
. [.ph .cmd]#Создайте или измените параметр `CacheMode`:#
+
* Тип: [.keyword]*DWORD*
* Значение:
** 1 – если требуется кэшировать карточки;
** 2 – если требуется кэшировать файлы;
** 4 – если требуется кэшировать справочники.
+
Установите в `CacheMode` сумму значений, чтобы кэшировались карточки, файлы, справочники. Например, для кэширования только справочников и файлов, результирующее значение будет равно 2+4 = 6.

*Parent topic:* xref:../topics/ClientCache.adoc[Клиентский кэш данных]
