= Настройка кэширования данных

Режим клиентского кэширования для всех пользователей настраивается в "Консоли настройки {dv}" (см. документ _Модуль {pl}. Руководство администратора_, пункт "Сервер").

Если требуется, администратор может переопределить режим кэширования для отдельного пользователя или всех пользователей определенного компьютера.

. Откройте _Редактор реестра_ на компьютере пользователя, для которого нужно установить собственный режим кэширования.
. Перейдите к ветке: `HKLM\SOFTWARE\{dv}\Platform\5.5\ObjectManager`.
* `HKLM\SOFTWARE\{dv}\Platform\5.5\ObjectManager` -- чтобы настроить режим кэширования для всех пользователей компьютера;
* `HKCU\SOFTWARE\{dv}\Platform\5.5\ObjectManager` -- чтобы настроить режим кэширования для текущего пользователя.
+
Если раздел ObjectManager отсутствует, создайте его самостоятельно.
+
Локальная настройка в реестре приоритетнее настройки на сервере. Локальная настройка в ветке `HKCU` приоритетнее, чем настройка в ветке `HKLM`.
. Создайте или измените параметр `CacheMode`:
+
* Тип: *DWORD*
* Значение:
** 1 -- если требуется кэшировать карточки;
** 2 -- если требуется кэшировать файлы;
** 4 -- если требуется кэшировать справочники.
+
Установите в `CacheMode` сумму значений, чтобы кэшировались карточки, файлы, справочники. Например, для кэширования только справочников и файлов, результирующее значение будет равно 2+4 = 6.
