[[ariaid-title1]]
== Клиентский кэш данных

Кэш – промежуточный буфер с быстрым доступом, содержащий информацию, которая может быть запрошена с наибольшей вероятностью. Данные из кэша могут быть получены быстрее чем из БД. Также использование клиентского кэша призвано снизить нагрузку на сервер Docsvision.

По умолчанию клиентский кэш размещается в папках [.ph .filepath]`DVCache` и [.ph .filepath]`DVScriptCache` временной папки пользователя ([.ph .filepath]`<системный диск>:\Users\<UserName>\AppData\Local\Temp\`). Папка [.ph .filepath]`DVCache` предназначена для хранения данных карточек и файлов, а папка [.ph .filepath]`DVScriptCache` – для скриптов карточек.

Файлы кэша карточек хранятся в папке [.ph .filepath]`%temp%\DVCache\<Имя базы данных>\<Идентификатор пользователя>\`. Имя кэшированного файла формируется по шаблону _ИдентификаторФайла_ДатаИзмененияФайлаКакДробное.dat_.

* *xref:../topics/CacheConfig.adoc[Настройка кэширования данных]* +
* *xref:../topics/CacheClear.adoc[Очистка клиентского кэша]* +

*На уровень выше:* xref:../topics/Administrator_functions.adoc[Функции администратора]
