= Настройка предкэширования компонентов карточек

Компонент карточки -- программный класс, содержащий базовые методы и события карточки определенного типа. Данный компонент инициализируется (загружается) при каждом открытии карточки. Реализованный в {wincl}е механизм переиспользования компонента карточки подразумевает, что загруженный для карточки определенного типа с определенной разметкой компонент, будет повторно использован при следующих открытиях карточек данного типа с данной разметкой. Компонент типа карточки должен разрешать переиспользование.

[NOTE]
====
Компоненты карточек библиотеки "{bo}" поддерживают переиспользования.
====

Механизм _предкэширования компонентов карточек_ реализует превентивную загрузку компонентов, для которых разрешено переиспользование, до первого обращения к ним. Предкэширование выполняется при бездействии {wincl}а для каждого типа карточек, компоненты которых могут быть переиспользованы, для каждой разметки. Общее число экземпляров компонентов в кэше для типа карточки ограничено (по умолчанию -- 30).

[NOTE]
====
Использование механизма предкэширования повышает требования к количеству оперативной памяти пользовательского компьютера.
====

Предкэширование выполняется для типов карточек, для которых предкэширование xref:Navigator_Cards.adoc[включено] в справочнике _Системные настройки_.

Администратор может изменить настройки предкэширования или отключить использование данного механизма на компьютере пользователя.

. Откройте конфигурационный файл `[Каталог установки клиентской части {wincl}а]/Navigator.exe.config`.
. Перейдите к секции menu:*configuration* > *{dv}.platform.wpf.navigator* > *navigator*.
. Добавьте в секцию *navigator* элемент *cardcache* следующего вида:
+
[source,]
----
<cardcache ItemsPerCardTypeMaxCount="30" VirtualMemorySize="1024" ContiniousPrecache="True" Disabled="False" />
----
. Измените настройки предкэширования по умолчанию:
* `ItemsPerCardTypeMaxCount` -- максимальное число компонентов карточек, которое предкэшируется для каждого типа карточек, поддерживающего переиспользование;
* `VirtualMemorySize` -- лимит виртуальной памяти в МБ, выделенной {wincl}у, до достижения которого осуществляется предкэширование;
* `ContiniousPrecache` -- флаг постоянного предкэширования:
** значение "True" -- предкэширование будет осуществляться всегда, когда {wincl} бездействует;
+
[NOTE]
====
Постоянное предкэширование подразумевает, что в кэш будет загружен новый экземпляр компонента карточки, если существующий экземпляр используется.
====
** значение "False" -- предкэширование будет осуществлено однократно.
* `Disabled` -- флаг использования предкэширования:
** значение "True" -- предкэширование отключено;
** значение "False" -- предкэширование включено.
