= Настройка предкэширования компонентов карточек

Компонент карточки -- программный класс, содержащий базовые методы и события карточки определенного типа. Данный компонент инициализируется (загружается) при каждом открытии карточки. Реализованный в {wincl}е механизм переиспользования компонента карточки подразумевает, что загруженный для карточки определенного типа с определенной разметкой компонент, будет повторно использован при следующих открытиях карточек данного типа с данной разметкой. Компонент типа карточки должен разрешать переиспользование.

[NOTE]
====
[.note__title]#Note:# Компоненты карточек библиотеки "Базовые объекты" поддерживают переиспользования.
====

Механизм _предкэширования компонентов карточек_ реализует превентивную загрузку компонентов, для которых разрешено переиспользование, до первого обращения к ним. Предкэширование выполняется при бездействии {wincl}а для каждого типа карточек, компоненты которых могут быть переиспользованы, для каждой разметки. Общее число экземпляров компонентов в кэше для типа карточки ограничено (по умолчанию -- 30).

[NOTE]
====
[.note__title]#Note:# Использование механизма предкэширования повышает требования к количеству оперативной памяти пользовательского компьютера.
====

Предкэширование выполняется для типов карточек, для которых предкэширование xref:Navigator_Cards.adoc[включено] в справочнике _Системные настройки_.

Администратор может изменить настройки предкэширования или отключить использование данного механизма на компьютере пользователя.

. [.ph .cmd]#Откройте конфигурационный файл [.ph .filepath]`[Каталог установки клиентской части {wincl}а]/Navigator.exe.config`.#
. [.ph .cmd]#Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}.platform.wpf.navigator* > [.ph .uicontrol]*navigator*#.#
. [.ph .cmd]#Добавьте в секцию [.ph .uicontrol]*navigator* элемент [.ph .uicontrol]*cardcache* следующего вида:#
+
[source,pre,codeblock]
----
<cardcache ItemsPerCardTypeMaxCount="30" VirtualMemorySize="1024" ContiniousPrecache="True" Disabled="False" />
----
. [.ph .cmd]#Измените настройки предкэширования по умолчанию:#
* `ItemsPerCardTypeMaxCount` -- максимальное число компонентов карточек, которое предкэшируется для каждого типа карточек, поддерживающего переиспользование;
* `VirtualMemorySize` -- лимит виртуальной памяти в МБ, выделенной {wincl}у, до достижения которого осуществляется предкэширование;
* `ContiniousPrecache` -- флаг постоянного предкэширования:
** значение "True" -- предкэширование будет осуществляться всегда, когда {wincl} бездействует;
+
[NOTE]
====
[.note__title]#Note:# Постоянное предкэширование подразумевает, что в кэш будет загружен новый экземпляр компонента карточки, если существующий экземпляр используется.
====
** значение "False" -- предкэширование будет осуществлено однократно.
* `Disabled` -- флаг использования предкэширования:
** значение "True" -- предкэширование отключено;
** значение "False" -- предкэширование включено.

*Parent topic:* xref:../topics/Administrator_functions.adoc[Функции администратора]
