[[ariaid-title1]]
== Централизованная установка модуля «Windows-клиент» в домене

Основное клиентское приложение Windows-клиент может быть установлено централизованно при помощи Active Directory или других средств сетевого администрирования. Чтобы воспользоваться централизованной установкой через Active Directory, необходимо настроить групповую политику (group policy) для тех компьютеров и пользователей, которые должны иметь доступ к Docsvision.

[NOTE]
====
[.note__title]#Прим.:# Для устранения потенциальных сложностей, связанных с установкой при помощи политик, удобно воспользоваться средством, описанным в http://support.microsoft.com/kb/249621[Microsoft Knowledge Base Article 249621].
====

Все устанавливаемые пакеты MSI должны быть доступны пользователям по сети. При централизованной установке в домене можно воспользоваться:

* Инсталляцией только для пользователя: ветвь настроек [.ph .menucascade]#[.ph .uicontrol]*Конфигурация пользователя* > [.ph .uicontrol]*Конфигурация программ* > [.ph .uicontrol]*Установка программного обеспечения*# ([.ph .menucascade]#[.ph .uicontrol]*User Configuration* > [.ph .uicontrol]*Software Settings* > [.ph .uicontrol]*Software Installation*#) в режиме `Назначенный` (`Assigned`). В этом случае вы можете потребовать, чтобы клиентская часть ПО установилась автоматически при входе в систему при помощи опции [.keyword]*Устанавливать это приложение при входе в систему* ([.keyword]*Install this application at logon*). При наличии выбранной опции, в момент входа в систему ПО будет установлено в папку в профиле пользователя. Если опция не выбрана, приложение установлено не будет. 
* Инсталляцией для всего компьютера: ветвь настроек [.ph .menucascade]#[.ph .uicontrol]*Конфигурация компьютера* > [.ph .uicontrol]*Конфигурация программ* > [.ph .uicontrol]*Установка программного обеспечения*# ([.ph .menucascade]#[.ph .uicontrol]*Computer Configuration* > [.ph .uicontrol]*Software Settings* > [.ph .uicontrol]*Software Installation*#) в режиме `Назначенный` (`Assigned`); в этом случае программное обеспечение будет полностью установлено (вне зависимости от значения опции) при регистрации компьютера в сети.

[NOTE]
====
[.note__title]#Внимание:# Необходимо соблюдать выбранный режим развертывания, так как установка для всех пользователей не может заменить предыдущую установку для конкретного пользователя и наоборот.
====

[NOTE]
====
[.note__title]#Внимание:# Не используйте установку для конкретного пользователя для пользователей с включенным режимом `Перемещаемый профиль` (`Roaming     Profile`).
====

При централизованной установке ярлыки, создаваемые на рабочем столе пользователей, не будут содержать правильный адрес сервера. Для создания правильного ярлыка необходимо применить MST-преобразование, создание которого описано в пункте xref:Install_modify.adoc[Изменение параметров установки Модуля с помощью файла преобразования]. После создания MST-преобразование нужно добавить для пакета [.dfn .term]_DocsvisionClient<номер текущей версии>.msi_ в настройках групповой политики.

[NOTE]
====
[.note__title]#Прим.:# Регистрацию установочных пакетов совместно с MST-преобразованиями необходимо производить в режиме `Особый` (`Advanced`).
====

*На уровень выше:* xref:../topics/Administrator_functions.adoc[Функции администратора]
