= Централизованная установка модуля _{wincl}_ в домене

Основное клиентское приложение {wincl} может быть установлено централизованно при помощи Active Directory или других средств сетевого администрирования. Чтобы воспользоваться централизованной установкой через Active Directory, необходимо настроить групповую политику (group policy) для тех компьютеров и пользователей, которые должны иметь доступ к {dv}.

[NOTE]
====
Для устранения потенциальных сложностей, связанных с установкой при помощи политик, удобно воспользоваться средством, описанным в http://support.microsoft.com/kb/249621[Microsoft Knowledge Base Article 249621].
====

Все устанавливаемые пакеты MSI должны быть доступны пользователям по сети. При централизованной установке в домене можно воспользоваться:

* Инсталляцией только для пользователя: ветвь настроек menu:*Конфигурация пользователя* > *Конфигурация программ* > *Установка программного обеспечения* (menu:*User Configuration* > *Software Settings* > *Software Installation*) в режиме `Назначенный` (`Assigned`). В этом случае вы можете потребовать, чтобы клиентская часть ПО установилась автоматически при входе в систему при помощи опции *Устанавливать это приложение при входе в систему* (*Install this application at logon*). При наличии выбранной опции, в момент входа в систему ПО будет установлено в папку в профиле пользователя. Если опция не выбрана, приложение установлено не будет.
* Инсталляцией для всего компьютера: ветвь настроек menu:*Конфигурация компьютера* > *Конфигурация программ* > *Установка программного обеспечения* (menu:*Computer Configuration* > *Software Settings* > *Software Installation*) в режиме `Назначенный` (`Assigned`); в этом случае программное обеспечение будет полностью установлено (вне зависимости от значения опции) при регистрации компьютера в сети.

[CAUTION]
====
Необходимо соблюдать выбранный режим развертывания, так как установка для всех пользователей не может заменить предыдущую установку для конкретного пользователя и наоборот.
====

[CAUTION]
====
Не используйте установку для конкретного пользователя для пользователей с включенным режимом `Перемещаемый профиль` (`Roaming     Profile`).
====

При централизованной установке ярлыки, создаваемые на рабочем столе пользователей, не будут содержать правильный адрес сервера. Для создания правильного ярлыка необходимо применить MST-преобразование, создание которого описано в пункте xref:Install_modify.adoc[Изменение параметров установки модуля с помощью файла преобразования]. После создания MST-преобразование нужно добавить для пакета _{dv}Client<номер текущей версии>.msi_ в настройках групповой политики.

[NOTE]
====
Регистрацию установочных пакетов совместно с MST-преобразованиями необходимо производить в режиме `Особый` (`Advanced`).
====
