= Предварительное кэширование компонентов карточек

Компонент карточки -- программный класс, содержащий базовые методы и события карточки определённого типа. Данный компонент инициализируется (загружается) при каждом открытии карточки.

В {wincl}е реализован механизм повторного использования компонентов карточки. Данный механизм позволяет использовать при следующих открытиях компонент, загруженный для определённого типа карточки с определённой разметкой. +
Компонент типа карточки должен разрешать повторное использование.

[NOTE]
====
Компоненты карточек библиотеки {bo} поддерживают повторное использование.
====

Механизм _предварительного кэширования компонентов карточек_ позволяет не загружать до первого обращения компоненты, для которых разрешено повторное использование. Предварительное кэширование выполняется при бездействии {wincl}а для каждого типа карточек, компоненты которых могут быть повторно использованы, для каждой разметки. Общее число экземпляров компонентов в кэше для типа карточки ограничено (по умолчанию -- `30`).

[NOTE]
====
Использование механизма предварительного кэширования повышает требования к объёму оперативной памяти пользовательского компьютера.
====

Предварительное кэширование выполняется для типов карточек, для которых предварительное кэширование xref:system-settings.adoc#cards[включено] в справочнике _Системные настройки_.

Администратор может изменить настройки предварительного кэширования или отключить использование данного механизма на компьютере пользователя.

. Откройте конфигурационный файл `Каталог-установки клиентской-части-{wincl}а/Navigator.dll.config`.
. Перейдите к секции menu:configuration[Docsvision.platform.wpf.navigator > navigator].
. Добавьте в секцию `navigator` элемент `cardcache` следующего вида:
+
[source]
----
<cardcache ItemsPerCardTypeMaxCount="30" VirtualMemorySize="1024" ContiniousPrecache="True" Disabled="False" />
----
+
. Измените настройки предварительного кэширования по умолчанию:
* `ItemsPerCardTypeMaxCount` -- максимальное число компонентов карточек, которые предварительного кэшируются для каждого типа карточек, поддерживающего повторное использование.
* `VirtualMemorySize` -- лимит виртуальной памяти в Мб, выделенной {wincl}у, до достижения которого осуществляется предварительное кэширование.
* `ContiniousPrecache` -- флаг постоянного предварительного кэширования:
** Значение `True` -- предварительное кэширование будет осуществляться всегда, когда {wincl} бездействует.
+
[NOTE]
====
Постоянное предварительное кэширование подразумевает, что в кэш будет загружен новый экземпляр компонента карточки, если существующий экземпляр используется.
====
+
** Значение `False` -- предварительное кэширование будет осуществлено однократно.
* `Disabled` -- флаг использования предварительного кэширования:
** Значение `True` -- предварительное кэширование отключено.
** Значение `False` -- предварительное кэширование включено.
* `Trace` -- включает и отключает трассировку предварительного кэширования.
** Значение `True` -- трассировка отключена.
** Значение `False` -- трассировка включена.
