= Предварительная компиляции компонентов

_Утилита предварительной компиляции приложений_ `NgenUtil.exe` предназначена для компиляции IL-кода .NET-компонентов клиентских частей модулей {dv} в машинный код. Данная процедура призвана повысить скорость *первого* открытия карточек.

Программа входит в пакет установки клиентской части модуля {pl}.

.Чтобы запустить программу:
. Откройте командную строку от имени администратора компьютера.
. Перейдите в каталог установки {wincl}а.
. Запустите команду:
+
[source,shell]
----
NgenUtil.exe /ExternalOnly
----
+
Будут предкомпилированы .NET-сборки сторонних производителей из подпапки `Components` каталога установки {wincl}а. +
Клиентские компоненты {dv} в данном случае не затрагиваются.
+
[NOTE]
====
Вызов программы происходит один раз для каждого пользователя или для каждого рабочего места в зависимости от того, как были установлены клиентские компоненты {dv}.
====
+
После выполнения процедуры загрузка .NET-компонентов карточек будет выполняться из папки `C:\Windows\assembly\NativeImages_v4.0.30319_32`, а не из каталога модуля. Данную особенность необходимо учитывать при обновлении версии модулей, т. к. обновленные компоненты не будут использоваться до помещения их в `NativeImages`.
+
Как правило, обновление не затрагивает сборки сторонних производителей, поэтому дополнительных действий после обновления версии не требуется, если это явно не указано в инструкции по обновлению.
+
. Также NgenUtil позволяет предкомпилировать все .NET-компоненты из каталога {wincl}а.
+
.Для этого запустите программу без флагов запуска:
[source,shell]
----
NgenUtil.exe
----
+
В данном случае также будут предкомпилированы компоненты {dv}. При обновлении версий клиентских модулей потребуется обновить образы сборок в `NativeImages`. Для этого NgenUtil нужно запустить с флагом `force`:
+
[source,shell]
----
NgenUtil.exe /force
----
+
Если были предкомпилированы только сторонние сборки и они были изменены в новой версии (будет указано в инструкции по обновлению), их можно обновить при помощи комбинации флагов `force` и `ExternalOnly`:
+
[source,shell]
----
NgenUtil.exe /ExternalOnly /force
----
