[[ariaid-title1]]
== Назначение и функции Модуля

«Docsvision 5. Windows-клиент» является [.dfn .term]_базовым модулем_ системы «Docsvision 5.5», который предоставляет клиентские программы для работы с системой Docsvision на персональном компьютере с ОС Windows:

. Windows-клиент – классическая клиентская программа Docsvision для пользователей, администраторов и инженеров Docsvision;
. Рабочее место администратора (РМА) – клиентская программа Docsvision для администраторов и инженеров Docsvision, выполненная в виде компонента ActiveX, запускаемого из веб-браузера Internet Explorer.
+
[NOTE]
====
[.note__title]#Прим.:# Далее, под «Windows-клиентом» будет подразумеваться программа «Windows-клиент», если отдельно не указано, что речь идет о Модуле.
====

Windows-клиент предоставляет следующие возможности:

* создание, копирование и удаление карточек и ярлыков [.dfn .term]_карточек_ Docsvision;
* конвертация карточек в [.dfn .term]_шаблоны карточек_;
* создание, копирование и удаление [.dfn .term]_папок_ Docsvision;
* настройка [.dfn .term]_представлений_ для папок;
* поиск карточек с использованием [.dfn .term]_полнотекстового_ и [.dfn .term]_атрибутивного поиска_;
* настройка свойств карточек и папок;
* экспорт данных из представления в файл *.XLS.

РМА предлагает аналогичные Windows-клиенту функции, а также предоставляет возможность настраивать общие для всех пользователей [.dfn .term]_поисковые запросы_ и представления.

Windows-клиент ориентирован на различные группы [.dfn .term]_конечных пользователей_:

* исполнители, выполняющие все операции по работе с документами, начиная от регистрации полученных документов, и заканчивая отправкой документов в архив;
* руководители среднего звена, использующие систему документооборота для исполнения или выдачи поручений, а также - согласования документов.

Конечным пользователям Docsvision рекомендуется работать в Windows-клиенте. РМА рекомендуется использовать только для настройки поисковых запросов и представлений, выполнения операций импорта данных из формата *.XML и других операций, которые недоступны в Windows-клиенте.

*На уровень выше:* xref:../topics/General_information.adoc[Общие сведения]
