[[ariaid-title1]]
== Необходимое программное обеспечение

=== Требования серверной части Модуля

. *Модули Docsvision*:
[loweralpha]
.. Серверная часть модуля «Docsvision 5. Платформа» версии 5.5.2 сборка 4553 и выше.
.. Серверная часть модуля «Docsvision 5. Базовые объекты» версии 5.5.3 сборка 5367 и выше.
.. Серверная часть приложения «Docsvision 5. Управление документами» версии 5.5.3 сборка 5316 и выше.
.. Серверная часть модуля «Docsvision 5. Управление процессами» версии 5.5.2 сборка 4224 и выше.
.. Серверная часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.2 сборка 4221 и выше.
.. Серверная часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.2 сборка 4203 и выше.

=== Требования клиентской части Модуля

. *Операционная система*
* Microsoft Windows 7 SP 1 (Enterprise, Professional, Ultimate);
* Microsoft Windows 8/8.1 (Pro, Enterprise)xref:#fntarg_1[^1^];
* Microsoft Windows 10 (Pro, Enterprise);
* или любая ОС, указанная в требованиях серверной части модуля «Docsvision 5. Платформа» (документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Платформа». Руководство администратора_#, пункт «Необходимое программное обеспечение»).
. *Модули Docsvision*:
[loweralpha]
.. Клиентская часть модуля «Docsvision 5. Платформа» версии 5.5.2 сборка 4553 и выше.
.. Клиентская часть модуля «Docsvision 5. Базовые объекты» версии 5.5.3 сборка 5367 и выше.
.. Клиентская часть приложения «Docsvision 5. Управление документами» версии 5.5.3 сборка 5316 и выше.
.. Клиентская часть модуля «Docsvision 5. Управление процессами» версии 5.5.2 сборка 4224 и выше.
.. Клиентская часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.2 сборка 4221 и выше.
.. Клиентская часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.2 сборка 4203 и выше.
. *Обязательное программное обеспечение*
[loweralpha]
.. Microsoft .NET Framework 4.6.1.
.. Microsoft Internet Explorerxref:#fntarg_2[^2^] версии 8, 9, 10 или 11.

Следующее программное обеспечение не является обязательным, но его отсутствие может повлиять на функциональные возможности Windows-клиента и РМА.

.[.table--title-label]##Табл. 1. ##[.title]##Дополнительное программное обеспечение##
[width="100%",cols="25%,75%",]
|===
|*Веб-браузер* (для открытия карточек по ссылке) a|
* +++32-разрядный+++ Microsoft Internet Explorer версии 8xref:#fntarg_3[^3^], 9, 10 или 11;
* Google Chrome версий с 19.0 по 72.0 с расширением «Docsvision Windows Client Launcher»;
* или Opera версий 12.0.0 - 23.0.0.

|*Microsoft Office* a|
+++32-разрядные+++ версии приложений Microsoft Office 2007, 2010, 2013 или 2016:

. Microsoft Word (для синхронизации полей карточки).
. Microsoft Lync 2010 или 2013, или Skype для бизнеса 2016 (для отображения статуса сотрудника в карточке).
+
Если установленная на компьютере программа «Microsoft Lync 2013» была обновлена на более раннюю версию (например, «Microsoft Lync 2010»), то для корректной работы функции отображения статуса сотрудника нужно удалить из реестра ветки программы «Microsoft Lync 2013»:

* [.ph .filepath]`HKCU\Software\IM Providers\Lync`,
* [.ph .filepath]`HKLM\Software\IM Providers\Lync`.
. Microsoft Outlook (для отправки карточек по электронной почте).
. Microsoft Excel (для экспорта представлений).
. Должен быть установлен компонент "Общие средства Office".

|===

* *xref:../topics/Software_citrix.adoc[Особенность использования системы доставки приложений Citrix XenApp]* +
* *xref:../topics/Preparing_to_Work_Install_Kaspersky.adoc[Совместимость с Kaspersky Endpoint Security 10]* +

*На уровень выше:* xref:../topics/Required_resources.adoc[Необходимые ресурсы]

xref:#fnsrc_1[^1^] Работа в ОС Windows 8 поддерживается только в режиме "Рабочего стола". Работа в режиме Metro, в том числе в Metro-Internet Explorer, не поддерживается.

xref:#fnsrc_2[^2^] Требуется для работы в РМА.

xref:#fnsrc_3[^3^] При работе в браузере Internet Explorer 8 в ОС Windows 7 открытие модального окна из карточки документа может приводить к блокированию основного окна Windows-клиента (до закрытия модального окна).
