[[ariaid-title1]]
== Предкомпиляции компонентов

[.dfn .term]_Утилита предкомпиляции приложений_ [.ph .filepath]`NgenUtil.exe` предназначена для компиляции IL-кода .NET-компонентов клиентских частей модулей Docsvision в машинный код. Данная процедура призвана повысить скорость *первого* открытия карточек.

Программа входит в пакет установки клиентской части модуля «Docsvision 5. Платформа».

Для запуска программы:

. Откройте командную строку от имени администратора компьютера.
. Перейдите в каталог установки Windows-клиента.
. Запустите команду:
+
[source,pre,codeblock]
----
NgenUtil.exe /ExternalOnly
----
+
Будут предкомпилированы .NET-сборки сторонних производителей из подпапки [.ph .filepath]`Components` каталога установки Windows-клиента. Клиентские компоненты Docsvision в данном случае не затрагиваются.
+
[NOTE]
====
[.note__title]#Прим.:# Вызов программы происходит один раз для каждого пользователя или для каждого рабочего места (в зависимости от того, как были установлены клиентские компоненты Docsvision).
====
+
После выполнения процедуры загрузка .NET-компонентов карточек будет выполняться из папки [.ph .filepath]`C:\Windows\assembly\NativeImages_v4.0.30319_32`, а не из каталога Модуля. Данную особенность необходимо учитывать при обновлении версии Модулей, т. к. обновленные компоненты не будут использоваться до помещения их в «NativeImages».
+
Как правило, обновление не затрагивает сборки сторонних производителей, поэтому дополнительных действий после обновления версии не требуется, если это явно не указано в инструкции по обновлению.
+
Также NgenUtil позволяет предкомпилировать все .NET-компоненты из каталога Windows-клиента. Для этого запустите программу без флагов запуска:

[source,pre,codeblock]
----
NgenUtil.exe
----
+
В данном случае также будут предкомпилированы компоненты Docsvision. При обновлении версий клиентских модулей потребуется обновить образы сборок в «NativeImages». Для этого NgenUtil нужно запустить с флагом [.ph .filepath]`force`:
+
[source,pre,codeblock]
----
NgenUtil.exe /force
----
+
Если были предкомпилированы только сторонние сборки и они были изменены в новой версии (будет указано в инструкции по обновлению), обновить только их сборки можно комбинацией флагов [.ph .filepath]`force` и [.ph .filepath]`ExternalOnly`:
+
[source,pre,codeblock]
----
NgenUtil.exe /ExternalOnly /force
----

*На уровень выше:* xref:../topics/Administrator_functions.adoc[Функции администратора]
