[[ariaid-title1]]
== Приложение B. Параметры запуска Windows-клиента из командной строки

=== Настройки Windows-клиента

* [.ph]#[.keyword .parmname]_ShowPanels_ – настройки панелей Windows-клиента#:
** [.ph]#0 – по умолчанию, отображается панель иерархии папок и представление#;
** [.ph]#1 – отображается только иерархия папок#;
** [.ph]#2 – отображается только представление#;
** [.ph]#3 – отображается представление и панель предварительного просмотра#;
** [.ph]#4 – отображается панель иерархии папок, представление и панель предварительного просмотра#;
** [.ph]#256 – показать Windows-клиент при открытии карточки (может быть прибавлено к одному из значений 0–4)#;
** [.ph]#512 – оставлять Windows-клиент работающим после того, как карточка, открытая по URL, закрывается пользователем (может быть прибавлено к одному из значений 0–4)#;
** [.ph]#1024 – скрыть панель инструментов Windows-клиента (может быть прибавлено к одному из значений 0–4)#;
** [.ph]#2048 – не показывать заставку при запуске Windows-клиента (может быть прибавлено к одному из значений 0–4)#;
+
[NOTE]
====
[.note__title]#Прим.:# Открыть [.dfn .term]_РМА_ можно только из адресной строки браузера. Из конфигурационного файла и командной строки открыть [.dfn .term]_РМА_ невозможно.
====
* [.ph]#[.keyword .parmname]_SkipVersionCheck_ – выполнение проверки соответствия версии установленного решения и версии, запрошенной сервером#:
** true – не выполнять проверку;
** false – выполнять проверку;
* [.keyword .parmname]_DisableVersionMismatchNotification_ – отключение отображения сообщения о несоответствии версий:
** true – отключить;
** false – не отключать;
* [.keyword .parmname]_IgnoreInvalidCert_ – при соединении по SSL, игнорировать некорректный сертификат сервера.
* [.keyword .parmname]_LogFile_ – путь к файлу с журналом Windows-клиента;
* [.keyword .parmname]_PrecacheCards_ – включает предкэширование компонент карточек при запуске Windows-клиента:
** true (по умолчанию) - предкэширование включено;
** false - предкэширование отключение;
* [.keyword .parmname]_SynchronousPrecache_ – включает режим синхронного (по умолчанию - асинхронный) предкэширования компонент карточек:
** true – включить режим синхронного предкэширования;
** false (по умолчанию) – отключить режим синхронного предкэширования, будет использован асинхронный режим;
* [.keyword .parmname]_RecentDocumentsMaxCount_ – максимальное число хранящихся в папке "Последние" ярлыков на карточки;
* [.keyword .parmname]_EnableVirtualizing_ – включает https://msdn.microsoft.com/ru-ru/library/system.windows.controls.virtualizationmode(v=vs.110).aspx[виртуализированный] режим работы панели Windows-клиента с деревом папок:
** true (по умолчанию) – включен;
** false – отключен.

=== Настройки соединения с сервером

* [.ph]#[.keyword .parmname]_DisableNTLM_ – запрещает встроенную аутентификацию (обратите внимание, что несколько окон Windows-клиента, открытые в одной сессии Windows под разными учетными записями, могут работать нестабильно в связи с особенностями работы Internet Explorer)#:
** true – не использовать встроенную аутентификацию;
** false – использовать встроенную аутентификацию;
* [.keyword .parmname]_Username_ – имя пользователя для подключения с базовой аутентификацией;
+
[NOTE]
====
[.note__title]#Прим.:# На некоторых системах вход с параметром [.keyword .parmname]_Username_ может приводить к входу в Docsvision под учетной записью пользователя текущей сессии Windows (если вход такого пользователя вообще возможен).
====
* [.keyword .parmname]_Password_ – пароль пользователя для подключения с базовой аутентификацией;
* [.keyword .parmname]_ServerUrl_ – базовый адрес сервера Docsvision вида http://servername/Docsvision;
* [.keyword .parmname]_BaseName_ – имя базы данных, к которой следует подключиться, игнорируя заданную по умолчанию в Консоли настроек;
* [.keyword .parmname]_Transport_ – тип транспортного канала для работы с сервисом Docsvision:
** 0 – веб-сервис (HTTP + SOAP);
** 10 – WCF сервис (HTTP + SOAP);
** 11 – WCF TCP сервис;
** 12 – WCF именованный канал (named pipe).
* [.keyword .parmname]_ConnectAddress_ – адрес Веб-сервиса Docsvision вида http://servername/Docsvision/StorageServer/StorageServerService.asmx.
* [.keyword .parmname]_InitialPort_ – начальный порт (по умолчанию - 8095) для поиска запущенных экземпляров Windows-клиента;
* [.keyword .parmname]_FinalPort_ – конечный порт (по умолчанию - 8105) для поиска запущенных экземпляров Windows-клиента.

Перечисленные выше параметры могут быть указаны непосредственно в конфигурационном файле Windows-клиента. В этом случае указывать их при запуске программы +++не нужно+++.

. Откройте файл [.ph .filepath]`<Каталог установки Windows-клиента>/Navigator.exe.config`.
. Добавьте требуемые параметры:
* параметры `RecentDocumentsMaxCount` и `EnableVirtualizing` – в элемент [.ph .filepath]`configuration/docsvision.platform.wpf.navigator/navigator/folders`;
* другие параметры – в элемент [.ph .filepath]`configuration/docsvision.platform.wpf.navigator/navigator/connection`
+
Следующий пример демонстрирует содержимое конфигурационного файла с добавленными параметрами `LogFile` и `EnableVirtualizing`.

[source,pre,codeblock]
----
<?xml version="1.0"?>
<configuration>
   <!-- Тут содержимое секции configSections -->
      
   <docsvision.platform.wpf.navigator>
      <navigator>
          <connection LogFile="C:/Logs/Windows_client.log"/>
          <folders EnableVirtualizing="True"/>
      </navigator>
   </docsvision.platform.wpf.navigator>
  
  <!-- Тут содержимое секций runtime и startup -->

</configuration>
----
+
*Следует обратить внимание на формат записи параметров*:
* названия параметров являются регистрозависимыми;
* значения параметров должны быть указаны в двойных кавычках.
. Сохраните изменения файла [.ph .filepath]`Navigator.exe.config`, перезапустите Windows-клиент.

*На уровень выше:* xref:../topics/Appendixes.adoc[Приложения]
