= Приложение A. Параметры запуска {wincl}а из веб-браузера

== Настройки окна {wincl}

* _ShowPanels_ – настройки панелей {wincl}а:
** 0 – по умолчанию отображается панель иерархии папок и представление;
** 1 – отображается только иерархия папок;
** 2 – отображается только представление;
** 3 – отображается представление и панель предварительного просмотра;
** 4 – отображается панель иерархии папок, представление и панель предварительного просмотра;
** 256 – показать {wincl} при открытии карточки (может быть прибавлено к одному из значений 0–4);
** 512 – оставлять {wincl} работающим после того, как карточка, открытая по URL, закрывается пользователем (может быть прибавлено к одному из значений 0–4);
** 1024 – скрыть панель инструментов {wincl}а (может быть прибавлено к одному из значений 0–4);
** 2048 – не показывать заставку при запуске {wincl}а (может быть прибавлено к одному из значений 0–4);
** 32768 – открыть _Рабочее место администратора_;
** 36864  – открыть _Рабочее место администратора_, используя при этом старый шаблон представлений (использовался до версии {dv} 4.3);
* _LangName_ (RUS – русский, ENU – английский – язык интерфейса пользователя (дополнительные языки указываются по тому же принципу);
* _KeepBrowserUI_ – скрывать ли меню и панели Internet Explorer;
* _RefreshTimeout_ – период обновления панели представления в секундах;
* _FolderID_ – идентификатор папки, отображаемой при старте;
* _ShortcutID_ – идентификатор ярлыка карточки, отображаемой при старте;
* _CardID_ – идентификатор карточки, отображаемой при старте;
* _ModeID_ – идентификатор режима, в котором отображается карточка;
* _ViewID_ – идентификатор представления папки, указанной в FolderID;
* _ActionID_ -- идентификатор команды открытия карточки, указанной в CardID;
* _Command_ -- дополнительная команда
** 0 (по умолчанию) -- активирует персональную папку сотрудника
** 1 -- активирует папку с идентификатором FolderID, используя представление ViewID
** 2 -- открывает карточку по ShortcutID в режиме ModeID
** 3 -- открывает карточку с идентификатором CardID
** 4 -- создает новую карточку типа, идентификатор которой указан в CardTypeID, в папке с идентификатором FolderID
* _SkipVersionCheck_ – выполнение проверки соответствия версии установленного решения и версии, запрошенной сервером:
** 0 – выполнять проверку;
** 1 – не выполнять проверку;
* _IgnoreInvalidCert_ – при соединении по SSL, игнорировать некорректный сертификат сервера.

== Настройки соединения

* _DisableNTLM_ -- запрещает встроенную аутентификацию (обратите внимание, что несколько окон {wincl}а, открытые в одной сессии Windows под разными учетными записями, могут работать нестабильно в связи с особенностями работы Internet Explorer):
** 0 – использовать встроенную аутентификацию;
** 1 – не использовать встроенную аутентификацию;
* _Username_ -- имя пользователя для подключения с базовой аутентификацией;
+
[NOTE]
====
На некоторых системах вход с параметром _Username_ может приводить к входу в {dv} под учетной записью пользователя текущей сессии Windows (если вход такого пользователя вообще возможен).
====
* _Password_ -- пароль пользователя для подключения с базовой аутентификацией;
* _ServerUrl_ -- базовый адрес сервера {dv} вида http://servername/{dv};
* _BaseName_ -- имя базы данных, к которой следует подключиться, игнорируя заданную по умолчанию в Консоли настроек;
* _Transport_ -- тип транспортного канала для работы с сервисом {dv}:
** 0 – веб-сервис (HTTP + SOAP);
** 10 – WCF сервис (HTTP + SOAP);
** 11 – WCF TCP сервис;
** 12 – WCF именованный канал (named pipe).
* _ConnectAddress_ -- адрес Веб-сервиса {dv} вида http://servername/{dv}/StorageServer/StorageServerService.asmx.

== Настройки инсталляции решений

* _InstallUILevel_ – уровень отображения пользовательского интерфейса инсталляций:
** 0 – используется настройки интерфейса по умолчанию;
** 1 – полностью автоматическая инсталляция;
** 2 – минимальный интерфейс;
** 3 – сокращенный интерфейс;
** 4 – полный интерфейс;
* _InstallAction_ –операция, которую выполняет {wincl} при инсталляции решений:
** 0 – инсталлировать необходимые библиотеки в режиме по умолчанию;
** 1 – не инсталлировать ничего;
** 2 – инсталлировать необходимые библиотеки полностью;
** 3 – инсталлировать необходимые библиотеки в режиме advertise, при этом в реестр записывается регистрация компонентов, а сами компоненты устанавливаются при первом использовании;
* _InstallLogPath_ – путь к папке, в которой будет создаваться лог файл для всех инсталлируемых компонентов;
* _InstallScope_ – область установки компонентов:
** 0 – для текущего пользователя;
** 1 – для всех пользователей;
** 2 – авто-распознавание, при наличии полномочий устанавливается для всех пользователей, иначе только для текущего пользователя;
* _InstallKeepOlder_– удалять ли клиентскую часть предыдущей версии {dv}, если она установлена:
** 0 – удалять клиентскую часть предыдущей версии {dv};
** 1 – сохранять клиентскую часть предыдущей версии {dv}.
