= Приложение B. Параметры запуска {wincl}а из командной строки

== Настройки {wincl}а

* _ShowPanels_ – настройки панелей {wincl}а:
** 0 – по умолчанию отображается панель иерархии папок и представление;
** 1 – отображается только иерархия папок;
** 2 – отображается только представление;
** 3 – отображается представление и панель предварительного просмотра;
** 4 – отображается панель иерархии папок, представление и панель предварительного просмотра;
** 256 – показать {wincl} при открытии карточки (может быть прибавлено к одному из значений 0–4);
** 512 – оставлять {wincl} работающим после того, как карточка, открытая по URL, закрывается пользователем (может быть прибавлено к одному из значений 0–4);
** 1024 – скрыть панель инструментов {wincl}а (может быть прибавлено к одному из значений 0–4);
** 2048 – не показывать заставку при запуске {wincl}а (может быть прибавлено к одному из значений 0–4);
+
[NOTE]
====
Открыть _РМА_ можно только из адресной строки браузера. Из конфигурационного файла и командной строки открыть _РМА_ невозможно.
====
* _SkipVersionCheck_ – выполнение проверки соответствия версии установленного решения и версии, запрошенной сервером:
** true – не выполнять проверку;
** false – выполнять проверку;
* _DisableVersionMismatchNotification_ -- отключение отображения сообщения о несоответствии версий:
** true -- отключить;
** false -- не отключать;
* _IgnoreInvalidCert_ – при соединении по SSL, игнорировать некорректный сертификат сервера.
* _LogFile_ -- путь к файлу с журналом {wincl}а;
* _PrecacheCards_ -- включает предкэширование компонент карточек при запуске {wincl}а:
** true (по умолчанию) -- предкэширование включено;
** false -- предкэширование отключение;
* _SynchronousPrecache_ -- включает режим синхронного (по умолчанию -- асинхронный) предкэширования компонент карточек:
** true -- включить режим синхронного предкэширования;
** false (по умолчанию) -- отключить режим синхронного предкэширования, будет использован асинхронный режим;
* _RecentDocumentsMaxCount_ -- максимальное число хранящихся в папке "Последние" ярлыков на карточки;
* _EnableVirtualizing_ -- включает https://msdn.microsoft.com/ru-ru/library/system.windows.controls.virtualizationmode(v=vs.110).aspx[виртуализированный] режим работы панели {wincl}а с деревом папок:
** true (по умолчанию) -- включен;
** false -- отключен.

== Настройки соединения с сервером

* _DisableNTLM_ -- запрещает встроенную аутентификацию (обратите внимание, что несколько окон {wincl}а, открытые в одной сессии Windows под разными учетными записями, могут работать нестабильно в связи с особенностями работы Internet Explorer):
** true – не использовать встроенную аутентификацию;
** false – использовать встроенную аутентификацию;
* _Username_ -- имя пользователя для подключения с базовой аутентификацией;
+
[NOTE]
====
На некоторых системах вход с параметром _Username_ может приводить к входу в {dv} под учетной записью пользователя текущей сессии Windows (если вход такого пользователя вообще возможен).
====
* _Password_ -- пароль пользователя для подключения с базовой аутентификацией;
* _ServerUrl_ -- базовый адрес сервера {dv} вида http://servername/{dv};
* _BaseName_ -- имя базы данных, к которой следует подключиться, игнорируя заданную по умолчанию в Консоли настроек;
* _Transport_ -- тип транспортного канала для работы с сервисом {dv}:
** 0 – веб-сервис (HTTP + SOAP);
** 10 – WCF сервис (HTTP + SOAP);
** 11 – WCF TCP сервис;
** 12 – WCF именованный канал (named pipe).
* _ConnectAddress_ -- адрес Веб-сервиса {dv} вида http://servername/{dv}/StorageServer/StorageServerService.asmx.
* _InitialPort_ -- начальный порт (по умолчанию -- 8095) для поиска запущенных экземпляров {wincl}а;
* _FinalPort_ -- конечный порт (по умолчанию -- 8105) для поиска запущенных экземпляров {wincl}а.

Перечисленные выше параметры могут быть указаны непосредственно в конфигурационном файле {wincl}а. В этом случае указывать их при запуске программы +++не нужно+++.

. Откройте файл `<Каталог установки {wincl}а>/Navigator.exe.config`.
. Добавьте требуемые параметры:
* параметры `RecentDocumentsMaxCount` и `EnableVirtualizing` -- в элемент `configuration/{dv}.platform.wpf.navigator/navigator/folders`;
* другие параметры -- в элемент `configuration/{dv}.platform.wpf.navigator/navigator/connection`
+
Следующий пример демонстрирует содержимое конфигурационного файла с добавленными параметрами `LogFile` и `EnableVirtualizing`.

[source,]
----
<?xml version="1.0"?>
<configuration>
   <!-- Тут содержимое секции configSections -->
      
   <{dv}.platform.wpf.navigator>
      <navigator>
          <connection LogFile="C:/Logs/Windows_client.log"/>
          <folders EnableVirtualizing="True"/>
      </navigator>
   </{dv}.platform.wpf.navigator>
  
  <!-- Тут содержимое секций runtime и startup -->

</configuration>
----
+
*Следует обратить внимание на формат записи параметров*:
* названия параметров являются регистрозависимыми;
* значения параметров должны быть указаны в двойных кавычках.
. Сохраните изменения файла `Navigator.exe.config`, перезапустите {wincl}.
