[[ariaid-title1]]
== Приложение A. Параметры запуска Windows-клиента из веб-браузера

=== Настройки окна Windows-клиент

* [#concept_pg5_wvv_hdb__ShowPanels .ph]#[.keyword .parmname]_ShowPanels_ – настройки панелей Windows-клиента#:
** [#concept_pg5_wvv_hdb__ShowPanels_0 .ph]#0 – по умолчанию, отображается панель иерархии папок и представление#;
** [#concept_pg5_wvv_hdb__ShowPanels_1 .ph]#1 – отображается только иерархия папок#;
** [#concept_pg5_wvv_hdb__ShowPanels_2 .ph]#2 – отображается только представление#;
** [#concept_pg5_wvv_hdb__ShowPanels_3 .ph]#3 – отображается представление и панель предварительного просмотра#;
** [#concept_pg5_wvv_hdb__Show_panels_4 .ph]#4 – отображается панель иерархии папок, представление и панель предварительного просмотра#;
** [#concept_pg5_wvv_hdb__ShowPanels_256 .ph]#256 – показать Windows-клиент при открытии карточки (может быть прибавлено к одному из значений 0–4)#;
** [#concept_pg5_wvv_hdb__ShowPanels_512 .ph]#512 – оставлять Windows-клиент работающим после того, как карточка, открытая по URL, закрывается пользователем (может быть прибавлено к одному из значений 0–4)#;
** [#concept_pg5_wvv_hdb__ShwPanels_1024 .ph]#1024 – скрыть панель инструментов Windows-клиента (может быть прибавлено к одному из значений 0–4)#;
** [#concept_pg5_wvv_hdb__ShowPanels_2048 .ph]#2048 – не показывать заставку при запуске Windows-клиента (может быть прибавлено к одному из значений 0–4)#;
** 32768 – открыть «Рабочее место Администратора»;
** 36864  – открыть «Рабочее место Администратора», используя при этом старый шаблон представлений (использовался до версии Docsvision 4.3);
* [.keyword .parmname]_LangName_ (RUS – русский, ENU – английский – язык интерфейса пользователя (дополнительные языки указываются по тому же принципу);
* [.keyword .parmname]_KeepBrowserUI_ – скрывать ли меню и панели Internet Explorer;
* [.keyword .parmname]_RefreshTimeout_ – период обновления панели представления в секундах;
* [.keyword .parmname]_FolderID_ – идентификатор папки, отображаемой при старте;
* [.keyword .parmname]_ShortcutID_ – идентификатор ярлыка карточки, отображаемой при старте;
* [.keyword .parmname]_CardID_ – идентификатор карточки, отображаемой при старте;
* [.keyword .parmname]_ModeID_ – идентификатор режима, в котором отображается карточка;
* [.keyword .parmname]_ViewID_ – идентификатор представления папки, указанной в FolderID;
* [.keyword .parmname]_ActionID_ – идентификатор команды открытия карточки, указанной в CardID;
* [.keyword .parmname]_Command_ – дополнительная команда
** 0 (по умолчанию) - активирует персональную папку сотрудника
** 1 - активирует папку с идентификатором FolderID, используя представление ViewID
** 2 - открывает карточку по ShortcutID в режиме ModeID
** 3 - открывает карточку с идентификатором CardID
** 4 - создает новую карточку типа, идентификатор которой указан в CardTypeID, в папке с идентификатором FolderID
* [#concept_pg5_wvv_hdb__SkipVersionCheck .ph]#[.keyword .parmname]_SkipVersionCheck_ – выполнение проверки соответствия версии установленного решения и версии, запрошенной сервером#:
** 0 – выполнять проверку;
** 1 – не выполнять проверку;
* [#concept_pg5_wvv_hdb__IgnoreInvalidCert]#[.keyword .parmname]_IgnoreInvalidCert_ – при соединении по SSL, игнорировать некорректный сертификат сервера.#

=== Настройки соединения

* [#concept_pg5_wvv_hdb__DisableNTLM .ph]#[.keyword .parmname]_DisableNTLM_ – запрещает встроенную аутентификацию (обратите внимание, что несколько окон Windows-клиента, открытые в одной сессии Windows под разными учетными записями, могут работать нестабильно в связи с особенностями работы Internet Explorer)#:
** 0 – использовать встроенную аутентификацию;
** 1 – не использовать встроенную аутентификацию;
* [#concept_pg5_wvv_hdb__Username]#[.keyword .parmname]_Username_ – имя пользователя для подключения с базовой аутентификацией;#
+
[NOTE]
====
[.note__title]#Прим.:# На некоторых системах вход с параметром [.keyword .parmname]_Username_ может приводить к входу в Docsvision под учетной записью пользователя текущей сессии Windows (если вход такого пользователя вообще возможен).
====
* [#concept_pg5_wvv_hdb__Password]#[.keyword .parmname]_Password_ – пароль пользователя для подключения с базовой аутентификацией;#
* [#concept_pg5_wvv_hdb__ServerUrl]#[.keyword .parmname]_ServerUrl_ – базовый адрес сервера Docsvision вида http://servername/Docsvision;#
* [#concept_pg5_wvv_hdb__BaseName]#[.keyword .parmname]_BaseName_ – имя базы данных, к которой следует подключиться, игнорируя заданную по умолчанию в Консоли настроек;#
* [#concept_pg5_wvv_hdb__Transport]#[.keyword .parmname]_Transport_ – тип транспортного канала для работы с сервисом Docsvision:#
** 0 – веб-сервис (HTTP + SOAP);
** 10 – WCF сервис (HTTP + SOAP);
** 11 – WCF TCP сервис;
** 12 – WCF именованный канал (named pipe).
* [#concept_pg5_wvv_hdb__ConnectAddress]#[.keyword .parmname]_ConnectAddress_ – адрес Веб-сервиса Docsvision вида http://servername/Docsvision/StorageServer/StorageServerService.asmx.#

=== Настройки инсталляции решений

* [.keyword .parmname]_InstallUILevel_ – уровень отображения пользовательского интерфейса инсталляций:
** 0 – используется настройки интерфейса по умолчанию;
** 1 – полностью автоматическая инсталляция;
** 2 – минимальный интерфейс;
** 3 – сокращенный интерфейс;
** 4 – полный интерфейс;
* [.keyword .parmname]_InstallAction_ –операция, которую выполняет Windows-клиент при инсталляции решений:
** 0 – инсталлировать необходимые библиотеки в режиме по умолчанию;
** 1 – не инсталлировать ничего;
** 2 – инсталлировать необходимые библиотеки полностью;
** 3 – инсталлировать необходимые библиотеки в режиме advertise, при этом в реестр записывается регистрация компонентов, а сами компоненты устанавливаются при первом использовании;
* [.keyword .parmname]_InstallLogPath_ – путь к папке, в которой будет создаваться лог файл для всех инсталлируемых компонентов;
* [.keyword .parmname]_InstallScope_ – область установки компонентов:
** 0 – для текущего пользователя;
** 1 – для всех пользователей;
** 2 – авто-распознавание, при наличии полномочий устанавливается для всех пользователей, иначе только для текущего пользователя;
* [.keyword .parmname]_InstallKeepOlder_– удалять ли клиентскую часть предыдущей версии Docsvision, если она установлена:
** 0 – удалять клиентскую часть предыдущей версии Docsvision;
** 1 – сохранять клиентскую часть предыдущей версии Docsvision.

*На уровень выше:* xref:../topics/Appendixes.adoc[Приложения]
