= Запуск {wincl}а с дополнительными параметрами

Пользователь может самостоятельно переопределить некоторые стандартные настройки {wincl}а, влияющие на запуск и/или работу клиента, с помощью дополнительных параметров запуска, которые можно передать двумя способами:

* запустить {wincl} из веб-браузера, указав параметры в адресной строке;
* запустить {wincl} из командной строки, перечислив в ней требуемые параметры.

[[concept_ozb_qk2_5db__section_lkx_kr2_5db]]
== Запуск {wincl}а с дополнительными параметрами из веб-браузера

Для запуска {wincl}а из веб-браузера достаточно перейти в поддерживаемом браузере по адресу стартовой страницы `http://[имя сервера {dv}]/[имя виртуальной папки {dv}]` -- {wincl} будет запущен под учетной записью пользователя текущей сессии Windows.

[NOTE]
====
В веб-браузере Opera текущая вкладка не закрывается.
====

Чтобы открыть {wincl} с дополнительными параметрами, нужно указать их после адреса стартовой страницы: `http://[имя сервера {dv}]/[имя виртуальной папки {dv}]?param1=value1&param2=value2`

Примеры запуска {wincl}а:

* с указанием рабочей базы данных: `http://server.ent.com/{dv}/?basename=имя_бд`;
* с использованием базовой аутентификации (будет затребована учетная запись и пароль пользователя): `http://server.ent.com/{dv}/?disablentlm=1`;
* с указанием языка пользовательского интерфейса: `http://server.ent.com/{dv}/?LangName=XXX`.

Полный список параметров запуска {wincl}а из веб-браузера приведен в xref:Appendix_A.adoc[Приложении A].

== Запуск {wincl}а с дополнительными параметрами из командной строки

Для запуска {wincl}а с параметрами в командной строке следует указать данные в формате: `[каталог установки модуля]/Navigator.exe /<ключ> <значение ключа>`.

Примеры запуска {wincl}а:

* с использованием базовой аутентификации: `C:\Program Files\{dv}\5.5\Client\Navigator.exe /DisableNTLM true`;
* с указанием открываемой карточки: `C:\Program Files\{dv}\5.5\Client\Navigator.exe /CardID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.

Полный список параметров запуска {wincl}а из командной строки приведен в xref:Appendix_B.adoc[Приложении B].
