[[ariaid-title1]]
== Запуск Windows-клиента с дополнительными параметрами

Пользователь может самостоятельно переопределить некоторые стандартные настройки Windows-клиента, влияющие на запуск и/или работу клиента, с помощью дополнительных параметров запуска, которые можно передать двумя способами:

* запустить Windows-клиент из веб-браузера, указав параметры в адресной строке;
* запустить Windows-клиент из командной строки, перечислив в ней требуемые параметры.

[[concept_ozb_qk2_5db__section_lkx_kr2_5db]]
=== Запуск Windows-клиента с дополнительными параметрами из веб-браузера

Для запуска Windows-клиента из веб-браузера достаточно перейти в поддерживаемом браузере по адресу стартовой страницы [.ph .filepath]`http://[имя сервера Docsvision]/[имя виртуальной папки Docsvision]` – Windows-клиент будет запущен под учетной записью пользователя текущей сессии Windows.

[NOTE]
====
[.note__title]#Прим.:# В веб-браузере Opera текущая вкладка не закрывается.
====

Чтобы открыть Windows-клиент с дополнительными параметрами, нужно указать их после адреса стартовой страницы: [.ph .filepath]`http://[имя сервера Docsvision]/[имя виртуальной папки Docsvision]?param1=value1&param2=value2`

Примеры запуска Windows-клиента:

* с указанием рабочей базы данных: [.ph .filepath]`http://server.ent.com/Docsvision/?basename=имя_бд`;
* с использованием базовой аутентификации (будет затребована учетная запись и пароль пользователя): [.ph .filepath]`http://server.ent.com/Docsvision/?disablentlm=1`;
* с указанием языка пользовательского интерфейса: [.ph .filepath]`http://server.ent.com/Docsvision/?LangName=XXX`.

Полный список параметров запуска Windows-клиента из веб-браузера приведен в xref:Appendix_A.adoc[Приложении A].

=== Запуск Windows-клиента с дополнительными параметрами из командной строки

Для запуска Windows-клиента с параметрами в командной строке следует указать данные в формате: [.ph .filepath]`[каталог установки Модуля]/Navigator.exe /<ключ> <значение ключа>`.

Примеры запуска Windows-клиента:

* с использованием базовой аутентификации: [.ph .filepath]`C:\Program Files\Docsvision\5.5\Client\Navigator.exe /DisableNTLM true`;
* с указанием открываемой карточки: [.ph .filepath]`C:\Program Files\Docsvision\5.5\Client\Navigator.exe /CardID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.

Полный список параметров запуска Windows-клиента из командной строки приведен в xref:Appendix_B.adoc[Приложении B].

*На уровень выше:* xref:../topics/Application_run_winclient.adoc[Запуск Windows-клиента]
