= Запуск {wincl}а

Пользователь, запускающий {wincl}, должен быть зарегистрирован в системе {dv}.

{wincl} можно запустить одним из следующих способов:

* с помощью значка программы _{wincl}_ на рабочем столе;
* из меню *Пуск*: menu:*{dv} 5* > *{wincl}*;
* из поддерживаемого веб-браузера (см. документ _Модуль _{wincl}_. Руководство администратора_, пункт "Необходимое программное обеспечение"): перейти по адресу стартовой страницы сервера {dv} `http://[имя сервера {dv}]/[имя виртуальной папки {dv}]/StartPage.aspx`;
* из программы "Личный помощник" (см. документ _Приложение "{dv} 5. Делопроизводство 4.5". Руководство пользователя_, пункт "Запуск программы _{wincl}_).

Будет открыто окно {wincl}а с папкой, которая xref:Navigator_settings_home_folder.adoc[выбрана домашней папкой].

При запуске {wincl}а может возникнуть ошибка "Номера версий системных компонент {wincl}а {dv} (...) и сервера {dv} (...) различаются", если установленная версия {wincl}а не соответствует требуемой (сервером {dv}). Для исправления ошибки необходимо обновить установленную версию {wincl}а.

* *xref:../topics/Application_run_adv.adoc[Запуск {wincl}а с дополнительными параметрами]* +
