[[ariaid-title1]]
== Запуск Windows-клиента

Пользователь, запускающий Windows-клиент, должен быть зарегистрирован в системе Docsvision.

Windows-клиент можно запустить одним из следующих способов:

* с помощью значка программы «Windows-клиент» на рабочем столе;
* из меню [.ph .uicontrol]*Пуск*: [.ph .menucascade]#[.ph .uicontrol]*Docsvision 5* > [.ph .uicontrol]*Windows-клиент*#;
* из поддерживаемого веб-браузера (см. документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Windows-клиент». Руководство администратора_#, пункт «Необходимое программное обеспечение»): перейти по адресу стартовой страницы сервера Docsvision [.ph .filepath]`http://[имя сервера Docsvision]/[имя виртуальной папки Docsvision]/StartPage.aspx`;
* из программы «Личный помощник» (см. документ [.ph]#[.dfn .term]_Приложение «Docsvision 5. Делопроизводство 4.5». Руководство пользователя_#, пункт «Запуск программы «Windows-клиент»).

Будет открыто окно Windows-клиента с папкой, которая xref:Navigator_settings_home_folder.adoc[выбрана домашней папкой].

При запуске Windows-клиента может возникнуть ошибка «Номера версий системных компонент Windows-клиента Docsvision (...) и сервера Docsvision (...) различаются», если установленная версия Windows-клиента не соответствует требуемой (сервером Docsvision). Для исправления ошибки необходимо обновить установленную версию Windows-клиента.

* *xref:../topics/Application_run_adv.adoc[Запуск Windows-клиента с дополнительными параметрами]* +

*Parent topic:* xref:../topics/Preparationfor_work.adoc[Подготовка к работе]
