= Архивирование данных

Архив {dv} предназначен для хранения данных, представляющих интерес для организации, но не используемых в её повседневной деятельности.

В _{dv}_ в архив могут быть помещены карточки всех типов, входящих в приложения _{dm}_ и _{wf}_, и карточки тех созданных пользователями типов, для которых предусмотрена архивация.

Находящуюся в архиве карточку можно найти расширенным поиском, просмотреть её данные в представлении, открыть в режиме только для чтения и разархивировать.

Все остальные действия над заархивированной карточкой невозможны, для их совершения карточку необходимо разархивировать.

[#status]
== Статусы архивирования

.Объект {dv} может иметь один из четырех статусов архивирования:
Не архивирован::
объект не архивирован, с ним можно полноценно работать. Данный статус присваивается карточке по умолчанию в момент создания.

Архивирован::
Объект находится в архиве, работа с данными архива запрещена.
+
Карточка получает статус `Архивирована` или `Не архивирована` при установке или снятии флага `*Архивирована*`. Флаг расположен на вкладке _Общие_ в окне свойств карточки.

Подготовлен к архивации::
Объект скоро будет помещён в архив, его данные всё ещё находятся в оперативных таблицах, но работать с ними запрещено.

Подготовлен к деархивации::
объект скоро будет извлечен из архива, его данные всё ещё находятся в архивных таблицах, работать с ними запрещено.
+
Если архивирование или разархивирование карточки предполагается отложить на определённый промежуток времени, администратор может самостоятельно разработать скрипт, который будет регулировать статус `Подготовлен к архивации` или `Подготовлен к деархивации`. Временя архивирования настраивается в программе {cns}.

[#archive-users]
== Пользователи, имеющие право работать с архивными данными

Архивирование данных является административной задачей, рядовой пользователь не имеет прав на выполнение этой операции.

.Работать с архивом могут только пользователи, включённые в следующие группы на сервере {dv} или их аналоги в справочнике сотрудников:
{dv-arch-ops-serv}::
Включённый в эту группу пользователь может архивировать, разархивировать и находить в архиве только те карточки, на работу с которыми у него есть права. +
Минимальные требования -- права на чтение.
{dv-admins-serv}::
Пользователь, входящий в эту группу, может архивировать и разархивировать карточки, на которые у него есть права, найти в архиве любую карточку и, при желании, отобразить карточки, помеченные как архивированные, в РМА.
{dv-power-users-serv}::
Пользователи, входящие в эту группу, имеют возможность чтения всех карточек системы и имеют права оператора архива, аналогичные правам *{dv-admins-serv}*.
{dv-sec-admins-serv}::
Пользователи, входящие в эту группу, обладают всеми правами {dv-admins-serv}, а также могут изменять уровни доступа, назначенные субъектам и объектам системы.

Для всех остальных пользователей карточки, помещённые в архив, недоступны и не отображаются в РМА и в {wincl}е.
