= Архивирование данных

Архив _{dv}_ предназначен для хранения данных, представляющих интерес для организации, но не используемых в её повседневной деятельности. В _{dv} 5_ в архив могут быть помещены карточки всех типов, входящих в приложения _{dm}_ и _{wf}_, и карточки тех созданных пользователями типов, для которых предусмотрена архивация.

Находящуюся в архиве карточку можно найти расширенным поиском, просмотреть её данные в представлении, открыть в режиме только для чтения и разархивировать.

Все остальные действия над заархивированной карточкой невозможны, для их совершения карточку необходимо разархивировать.

== Статусы архивирования

Объект {dv} может иметь один из четырех статусов архивирования:

. `Не архивирован`: объект не архивирован, с ним можно полноценно работать. Данный статус присваивается карточке по умолчанию в момент создания.
. `Архивирован`: объект находится в архиве, работа с данными архива запрещена.
. `Подготовлен к архивации`: объект скоро будет помещен в архив, его данные все еще находятся в оперативных таблицах, но работать с ними запрещено.
. `Подготовлен к деархивации`: объект скоро будет извлечен из архива, его данные все еще находятся в архивных таблицах, работать с ними запрещено.

Статус `Архивирована`/`Не архивирована` карточка получает при установке/снятии флага *Архивирована* (расположен на вкладке *Общие* окна свойств карточки). Статус `Подготовлен к      архивации`/`Подготовлен к деархивации` устанавливается программно специальным скриптом (разрабатывается самостоятельно администратором системы), если архивирование/разархивирование карточки предполагается отложить на определенный промежуток времени. Настройка времени архивирования выполняется в программе {cns}.