[[ariaid-title1]]
== Пользователи, которым разрешена работа с архивными данными

Архивирование данных является административной задачей, рядовой пользователь не имеет прав на выполнение этой операции.

Работать с архивом могут только пользователи, включенные в следующие группы:

Docsvision Archive Operators::
  Включенный в эту группу пользователь может архивировать, разархивировать и находить в архиве только те карточки, на работу с которыми у него есть права (минимальные требования – права на чтение).
Docsvision Administrators::
  Пользователь, входящий в эту группу, может архивировать и разархивировать карточки, на которые у него есть права, найти в архиве любую карточку и, при желании, отобразить карточки, помеченные как архивированные, в РМА.
Docsvision Power Users::
  Пользователи, входящие в эту группу, имеют возможность чтения всех карточек системы и имеют права оператора архива, аналогичные правам [.keyword .parmname]_Docsvision Administrators_.
Docsvision Security Administrators::
  Пользователи, входящие в эту группу, обладают всеми правами [.keyword .parmname]_Docsvision Administrators_, а также могут изменять уровни доступа, назначенные субъектам и объектам системы.

Для всех остальных пользователей карточки, помещенные в архив, недоступны и не отображаются в [.dfn .term]_РМА_ и в [.dfn .term]_Windows-клиенте_.

*На уровень выше:* xref:../topics/Archiving_Data.adoc[Архивирование данных]
