= Приложение A. Параметры запуска {wincl}а из веб-браузера

== Настройки окна {wincl}

include::partial$appendix.adoc[tags=2048]
** `32768` -- открыть _Рабочее место администратора_.
** `36864` -- открыть _Рабочее место администратора_, используя при этом старый шаблон представлений (использовался до версии {dv} 4.3).
* `LangName`: `RUS` -- русский, `ENU` -- английский -- язык интерфейса пользователя. Дополнительные языки указываются по тому же принципу.
* `KeepBrowserUI` -- скрывать ли меню и панели Internet Explorer.
* `RefreshTimeout` -- период обновления панели представления в секундах.
* `FolderID` -- идентификатор папки, отображаемой при старте.
* `ShortcutID` -- идентификатор ярлыка карточки, отображаемой при старте.
* `CardID` -- идентификатор карточки, отображаемой при старте.
* `ModeID` -- идентификатор режима, в котором отображается карточка.
* `ViewID` -- идентификатор представления папки, указанной в FolderID.
* `ActionID` -- идентификатор команды открытия карточки, указанной в `CardID`.
* `Command` -- дополнительная команда.
** `0` (по умолчанию) -- активирует персональную папку сотрудника
** `1` -- активирует папку с идентификатором `FolderID`, используя представление `ViewID`
** `2` -- открывает карточку по `ShortcutID` в режиме `ModeID`
** `3` -- открывает карточку с идентификатором `CardID`
** `4` -- создаёт новую карточку типа, идентификатор которой указан в `CardTypeID`, в папке с идентификатором `FolderID`
* `SkipVersionCheck` -- выполнение проверки соответствия версии установленного решения и версии, запрошенной сервером:
** `0` -- выполнять проверку.
** `1` -- не выполнять проверку.
* `IgnoreInvalidCert` -- при соединении по SSL, игнорировать некорректный сертификат сервера.

== Настройки соединения

include::partial$appendix.adoc[tags=disntlm]
+
** `0` -- использовать встроенную аутентификацию.
** `1` -- не использовать встроенную аутентификацию.
+
include::partial$appendix.adoc[tags=conn-address]

== Настройки инсталляции решений

* `InstallUILevel` -- уровень отображения пользовательского интерфейса инсталляций:
** `0` -- используется настройки интерфейса по умолчанию.
** `1` -- полностью автоматическая инсталляция.
** `2` -- минимальный интерфейс.
** `3` -- сокращенный интерфейс.
** `4` -- полный интерфейс.
* `InstallAction` -- операция, которую выполняет {wincl} при инсталляции решений:
** `0` -- инсталлировать необходимые библиотеки в режиме по умолчанию.
** `1` -- не инсталлировать ничего.
** `2` -- инсталлировать необходимые библиотеки полностью.
** `3` -- инсталлировать необходимые библиотеки в режиме `advertise`, при этом в реестр записывается регистрация компонентов, а сами компоненты устанавливаются при первом использовании.
* `InstallLogPath` -- путь к папке, в которой будет создаваться лог файл для всех инсталлируемых компонентов.
* `InstallScope` -- область установки компонентов:
** `0` -- для текущего пользователя.
** `1` -- для всех пользователей.
** `2` -- авто-распознавание, при наличии полномочий устанавливается для всех пользователей, иначе только для текущего пользователя.
* `InstallKeepOlder` -- удалять ли клиентскую часть предыдущей версии {dv}, если она установлена:
** `0` -- удалять клиентскую часть предыдущей версии {dv}.
** `1` -- сохранять клиентскую часть предыдущей версии {dv}.
