[[ariaid-title1]]
== Краткое описание возможностей

«Docsvision 5. Windows-клиент» является [.dfn .term]_базовым модулем_ системы «Docsvision 5.5», который предоставляет клиентские программы для работы с системой Docsvision на персональном компьютере с ОС Windows:

. Windows-клиент – классическая клиентская программа Docsvision всех групп пользователей ([.dfn .term]_конечных пользователей_, администраторов и инженеров);
. Рабочее место администратора (РМА) – ориентированная на администраторов и инженеров Docsvision клиентская программа Docsvision, выполненная в виде компонента ActiveX, исполняемого в веб-браузере Internet Explorer.
+
[NOTE]
====
[.note__title]#Прим.:# Далее, под «Windows-клиентом» будет подразумеваться клиентская программа «Windows-клиент», если отдельно не указано, что речь идет о модуле «Docsvision 5. Windows-клиент».
====

Windows-клиент предоставляет следующие возможности:

* авторизация пользователей в системе Docsvision;
* работа с карточками и папками Docsvision: создание, удаление, копирование, изменение свойств (в т.ч. свойств безопасности);
* работа со справочниками и конструкторами Docsvision;
* отображение данных карточек в формате представлений с возможностью сортировки и фильтрации;
* поиск карточек с использованием [.dfn .term]_полнотекстового_ и [.dfn .term]_атрибутивного поиска_;
* расширение функциональных возможностей с помощью устанавливаемых модулей Docsvision, а также [.dfn .term]_расширений_ Windows-клиента (библиотека DLL, предоставляющая дополнительную функциональность);
* экспорт данных из представления в файл *.XLS;
* локализация (возможность изменения языка пользовательского интерфейса);
* автоматическая загрузка и установка клиентских компонентов модулей и приложений Docsvision в соответствии с правилами установки.

РМА предоставляет аналогичные Windows-клиенту функции (с некоторыми ограничениями) с возможностью настраивать [.dfn .term]_поисковые запросы_ и [.dfn .term]_представления_.

Windows-клиент рассчитан на повседневную работу конечных пользователей, администраторов и инженеров Docsvision. РМА рекомендуется использовать для настройки поисковых запросов и представлений, выполнения операций импорта данных из формата *.XML, а также выполнения других операций, которые недоступны в Windows-клиенте.

*На уровень выше:* xref:../topics/Introduction.adoc[Введение]
