= Получение URL-адреса карточки и переход к карточке по её URL-адресу

Любая карточка _{dv}_ имеет свой URL-адрес. При вводе этого адреса в адресную строку веб-браузера указанная карточка будет открыта в _{wincl}е_.

Для того, чтобы скопировать в буфер обмена ссылку для открытия карточки:

. Выберите в области представления карточку, на которую нужно получить ссылку.
. Выполните любое из действий:
* в _Области представления_ правой клавишей мыши вызовите контекстное меню, затем выберите команду *Копировать URL на карточку*.
* перейдите на ленте на вкладку xref:ribbon-card[*Карточка*], затем нажмите на кнопку *Копировать URL на карточку*.
+
URL адрес для открытия выбранной карточки будет скопирован в буфер обмена.

Чтобы открыть карточку по имеющейся ссылке, перейдите по ней в поддерживаемом веб-браузере. После перехода будет открыта соответствующая карточка.

[NOTE]
====
При открытии карточки состояние окна {wincl}а не меняется. Так, например, если {wincl} был свернут в системный лоток, то он останется свернутым. Если {wincl} не был запущен, то он запускается свернутым в системный лоток.
====
