= Удаление и восстановление карточки или ярлыка карточки

Удаление карточек и ярлыков карточек производится в две стадии:

. *Первичное удаление карточки или ярлыка карточки*. Делает карточку (ярлык) недоступной для просмотра и редактирования; после первичного удаления карточку можно либо восстановить, либо окончательно удалить.
+
Список всех первично удаленных карточек можно просмотреть в папке *Корзина*. Список карточек, первично удаленных из какой-либо папки, можно отобразить/скрыть при помощи установки/снятия флага *Показывать удаленные* объекты в меню *Вид*, при этом строка с записью об удаленной карточке перечеркивается и подсвечивается серым цветом.
. *Окончательное удаление карточки*. После окончательного удаления восстановление карточки невозможно.

* *xref:../topics/Cards_Deleting_Cards.adoc[Удаление карточки]* +
* *xref:../topics/Cards_Deleting_Shortcut_Cards.adoc[Удаление ярлыка и карточки по ярлыку]* +
* *xref:../topics/Cards_Displays_PrimaryRemote_Objects.adoc[Отображение первично удаленных объектов]* +
* *xref:../topics/Cards_Recovery_Card_or_Shortcut.adoc[Восстановление карточки или ярлыка]* +
