= Получение URL-адреса карточки и переход к карточке по ее URL-адресу

Любая карточка _{dv}_ имеет свой URL-адрес. При вводе этого адреса в адресную строку браузера _РМА_ откроется на указанной карточке.

[NOTE]
====
[.note__title]#Важное замечание:# Открытие карточек по ссылке в 64-разрядном Internet Explorer не поддерживается.
====

Для получения URL-адрес карточки {dv} щелкните правой кнопкой по ее строке и выберите из контекстного меню команду [.ph .uicontrol]*Скопировать URL на карточку в буфер обмена*.

Чтобы перейти к карточке {dv} по ее URL-адресу, выполните следующие действия:

[[task_bfc_ln3_4n__steps_mhn_dbj_4n]]
. [.ph .cmd]#Скопируйте URL на карточку в буфер обмена. #
. [.ph .cmd]#Запустите браузер. #
. [.ph .cmd]#Введите из буфера обмена в адресную строку браузера URL-адрес карточки с помощью команды контекстного меню [.ph .uicontrol]*Вставить* ([.ph .uicontrol]*Paste*) или сочетания клавиш [.ph .uicontrol]*<Ctrl+V>*.#
+
После перехода будет открыта соответствующая карточка.
