= Восстановление карточки или ярлыка

Возможно восстановление только первично удаленных карточек или ярлыков, причем команда восстановления доступна как при просмотре папки, из которой была удалена карточка (ярлык), так и из системной папки *Корзина* (в которой отображаются все удаленные из системы карточки).

Чтобы восстановить первично удаленную карточку (ярлык), выделите ее правой кнопкой мыши и выберите в контекстном меню команду *Восстановить*.

Можно одновременно восстановить несколько карточек. Для этого необходимо выполнить следующие действия:

. Выделить карточки:
* если карточки следуют одна за другой, щелкните по строке с первой карточкой, а затем, удерживая клавишу *Shift*, по строке с последней карточкой;
* если карточки не следуют друг за другом, щелкните по первой из них, затем, удерживая клавишу *Ctrl*, по следующей; таким образом можно выделить любое количество карточек.
. Выбрать из контекстного меню команду *Восстановить*.

[NOTE]
====
При восстановлении папки, в которой находились карточки документов, будет восстановлена только папка (без карточек). Для восстановления карточек в папке нужно проделать такую же операцию с карточками документов.
====
