= Работа с ярлыками карточек

_Ярлыком карточки_ будем называть ссылку на карточку, которую пользователь в целях удобства обращения к карточке может разместить в любой удобной для него папке.

С помощью ярлыка можно осуществить следующие действия:

* перемещение ярлыка карточки в любую папку _РМА_ при помощи команды контекстного меню *Переместить ярлык в папку*;
* перемещение группы ярлыков карточек в любую папку _РМА_ при помощи команды контекстного меню *Переместить ярлыки в папку*;
* копирование ярлыка карточки в любую папку _РМА_ с помощью команды контекстного меню *Скопировать ярлык в папку*; при этом все данные карточки дублируются в указанной папке;
* копирование группы ярлыков карточек в любую папку _РМА_ с помощью команды контекстного меню *Скопировать ярлыки в папку*; при этом все данные карточек дублируются в указанной папке;
* удаление ярлыков карточек, при этом можно удалить как сам ярлык, так и карточку; для выполнения указанных действий предназначены пункты контекстного меню *Удалить карточку* и *Удалить ярлык* соответственно;
* размещение ярлыка некоторых типов карточек в любой папке _РМА_ (например, в приложении _{dm}_ -- при создании карточки по шаблону или при создании карточки из уже имеющейся карточки).

[NOTE]
====
_{bo}_ {dv} при работе в пользовательских папках создаются как ярлыки, соответствующие им карточки автоматически создаются в системной папке *Карточки*.
====
