= Работа с URL-адресом карточки

Любая карточка {dv} имеет свой URL-адрес. При вводе этого адреса в адресную строку веб-браузера указанная карточка будет открыта в {wincl}е.

.Чтобы скопировать в буфер обмена ссылку для открытия карточки:
. Выберите в области представления карточку, на которую нужно получить ссылку.
. Выполните любое из действий:
+
* В области представления правой клавишей мыши вызовите контекстное меню, затем выберите команду _Копировать URL на карточку_.
* Перейдите на ленте на вкладку "xref:ribbon-card.adoc[Карточка]", затем нажмите на кнопку *Копировать URL на карточку*.
+
URL адрес для открытия выбранной карточки будет скопирован в буфер обмена.
+
. Чтобы открыть карточку по имеющейся ссылке, вставьте её адресную строку поддерживаемомого веб-браузера. После перехода будет открыта соответствующая карточка.

[NOTE]
====
При открытии карточки из браузера состояние окна {wincl}а не меняется. Так, например, если {wincl} был свернут в системный лоток, то он останется свернутым. Если {wincl} не был запущен, то он запускается свернутым в системный лоток.
====
