[[ariaid-title1]]
== Получение URL-адреса карточки и переход к карточке по ее URL-адресу

Любая карточка [.dfn .term]_Docsvision_ имеет свой URL-адрес. При вводе этого адреса в адресную строку веб-браузера указанная карточка будет открыта в [.dfn .term]_Windows-клиенте_.

Для того, чтобы скопировать в буфер обмена ссылку для открытия карточки:

. [.ph .cmd]#Выберите в области представления карточку, на которую нужно получить ссылку.#
. [.ph .cmd]#Выполните любое из действий:#
* в [.dfn .term]_Области представления_ правой клавишей мыши вызовите контекстное меню, затем выберите команду [.keyword]*Копировать URL на карточку*.
* перейдите на ленте на вкладку xref:Interface_ribbon_card.html[[.keyword]*Карточка*], затем нажмите на кнопку [.keyword]*Копировать URL на карточку*.
+
URL адрес для открытия выбранной карточки будет скопирован в буфер обмена.

Чтобы открыть карточку по имеющейся ссылке, перейдите по ней в поддерживаемом веб-браузере. После перехода будет открыта соответствующая карточка.

[NOTE]
====
[.note__title]#Прим.:# При открытии карточки состояние окна Windows-клиента не меняется. Так, например, если Windows-клиент был свернут в системный лоток, то он останется свернутым. Если Windows-клиент не был запущен, то он запускается свернутым в системный лоток.
====

*На уровень выше:* xref:../topics/Cards.adoc[Работа с карточками]
