= Импорт данных карточки из файла формата .xml

Импорт данных карточки из файла формата .xml предназначен для переноса в систему _{dv}_ параметров карточки (или нескольких карточек), ранее сохраненной в файловой системе компьютера пользователя.

[NOTE]
====
Вытесненные (находящиеся во внешнем хранилище с отключенным режимом автовозврата) файлы не импортируются вместе с карточками, к которым они прикреплены.
====

Для того чтобы импортировать данные из файла формата .xml, выполните следующие действия:

. Откройте _РМА_.
. Выделите в списке папок ту, в которой будет создана карточка с импортированными данными.
. Выберите из контекстного меню команды menu:*Создать* > *Импортировать карточки...*.
+
Будет открыто стандартное диалоговое окно для выбора файла *Открыть*.
. В окне *Открыть* выберите файл (файлы), данные которого предполагается импортировать и нажмите кнопку *Открыть*.
+
Выбранный файл формата .xml помимо данных исходной карточки может содержать данные присоединенных к ней карточек. Если импорт проводит пользователь, включенный в группу _{dv} Administrators_ (_Администраторы {dv}_), то в _{dv}_ будут импортированы все данные, содержащиеся в файле. При импорте, осуществляемом рядовым пользователем, будут импортированы только данные исходной карточки.

[NOTE]
====
Если идентификатор какой-либо уже имеющейся в базе карточки совпадет с идентификатором импортируемой карточки, то ее данные будут заменены на новые, полученные в результате импорта. Однако, если при выборе команды *Импортировать карточки...* и последующем выборе файла для импорта удерживать нажатой клавишу *<Shift>*, то импортируемая карточка будет создана с другим идентификатором.
====

Данные файла .xml будут импортированы в {dv}.
