[[ariaid-title1]]
== Импорт данных карточки из файла формата .xml

Импорт данных карточки из файла формата .xml предназначен для переноса в систему [.dfn .term]_Docsvision_ параметров карточки (или нескольких карточек), ранее сохраненной в файловой системе компьютера пользователя.

[NOTE]
====
[.note__title]#Прим.:# Вытесненные (находящиеся во внешнем хранилище с отключенным режимом автовозврата) файлы не импортируются вместе с карточками, к которым они прикреплены.
====

Для того чтобы импортировать данные из файла формата .xml, выполните следующие действия:

. [.ph .cmd]#Откройте [.dfn .term]_РМА_. #
. [.ph .cmd]#Выделите в списке папок ту, в которой будет создана карточка с импортированными данными. #
. [.ph .cmd]#Выберите из контекстного меню команды [.ph .menucascade]#[.ph .uicontrol]*Создать* > [.ph .uicontrol]*Импортировать карточки...*#. #
+
Будет открыто стандартное диалоговое окно для выбора файла [.keyword .wintitle]*Открыть*.
. [.ph .cmd]#В окне [.keyword .wintitle]*Открыть* выберите файл (файлы), данные которого предполагается импортировать и нажмите кнопку [.ph .uicontrol]*Открыть*. #
+
Выбранный файл формата .xml помимо данных исходной карточки может содержать данные присоединенных к ней карточек. Если импорт проводит пользователь, включенный в группу [.keyword .parmname]_Docsvision Administrators_ ([.keyword .parmname]_Администраторы Docsvision_), то в [.dfn .term]_Docsvision_ будут импортированы все данные, содержащиеся в файле. При импорте, осуществляемом рядовым пользователем, будут импортированы только данные исходной карточки.

[NOTE]
====
[.note__title]#Прим.:# Если идентификатор какой-либо уже имеющейся в базе карточки совпадет с идентификатором импортируемой карточки, то ее данные будут заменены на новые, полученные в результате импорта. Однако, если при выборе команды [.ph .uicontrol]*Импортировать карточки...* и последующем выборе файла для импорта удерживать нажатой клавишу [.ph .uicontrol]*<Shift>*, то импортируемая карточка будет создана с другим идентификатором.
====

Данные файла .xml будут импортированы в Docsvision.

*На уровень выше:* xref:../topics/Cards_Export_Printing_Mailing_Data_Cards.adoc[Экспорт и импорт данных карточки, их печать и отправка по почте]
