= Поиск карточки

В {wincl}е доступны несколько способов поиска карточек:

Расширенный поиск по всему множеству карточек::
  Выполняется на основе поисковых запросов, которые можно сохранять для многократного использования. Результаты последнего поиска отображаются в виртуальной папке "xref:interface-navigation-area.adoc#search-results[Результаты поиска]". Пользователь может иметь различные права доступа к каждому поисковому запросу. В папку попадут только те карточки, к которым пользователю разрешен доступ. Описание данного вида поиска см. в разделе xref:Search_attributes.adoc[Атрибутивный поиск].
Полнотекстовый поиск карточек::
  Выполняется поиск карточек, которые содержат введённый текст. Поиск выполняется среди проиндексированных карточек, как в текущей активной папке, так и среди всех карточек системы. Описание данного вида поиска см. в разделе xref:Search_fulltext.adoc[Полнотекстовый поиск].
Поиск карточки в текущем представлении::
  Контекстный поиск карточек в текущем представлении по ключевой строке, которая может представлять собой сочетание символов, слово или фразу. В результате такого поиска будет выделена первая найденная карточка, отвечающая заданному условию. Для поиска по представлению может задаваться направление поиска вверх или вниз по списку.
Поиск карточки по штрих-коду::
  При наличии соответствующих настроек при сканировании штрих-кода ручным сканером может быть сразу же произведен автоматический поиск и открытие данной карточки. Также для поиска карточки по штрих-коду может быть сформирован поисковый запрос. В окне запроса курсор будет сразу находиться в поле поиска в ожидании информации от сканера, либо ввода кода с клавиатуры. Штрих-код передается в поле с символом Ввода после цифр. По умолчанию поиск по штрих-коду выполняется для карточек документов, однако, при необходимости может выполняться и для других карточек (например, карточек Заданий).
