[[ariaid-title1]]
== Удаление и восстановление карточки или ярлыка карточки

Удаление карточек и ярлыков карточек производится в две стадии:

. [.keyword]*Первичное удаление карточки или ярлыка карточки*. Делает карточку (ярлык) недоступной для просмотра и редактирования; после первичного удаления карточку можно либо восстановить, либо окончательно удалить.
+
Список всех первично удаленных карточек можно просмотреть в папке [.keyword]*Корзина*. Список карточек, первично удаленных из какой-либо папки, можно отобразить/скрыть при помощи установки/снятия флага [.ph .uicontrol]*Показывать удаленные* объекты в меню [.keyword]*Вид*, при этом строка с записью об удаленной карточке перечеркивается и подсвечивается серым цветом.
. [.keyword]*Окончательное удаление карточки*. После окончательного удаления восстановление карточки невозможно.

* *xref:../topics/Cards_Deleting_Cards.adoc[Удаление карточки]* +
* *xref:../topics/Cards_Deleting_Shortcut_Cards.adoc[Удаление ярлыка и карточки по ярлыку]* +
* *xref:../topics/Cards_Displays_PrimaryRemote_Objects.adoc[Отображение первично удаленных объектов]* +
* *xref:../topics/Cards_Recovery_Card_or_Shortcut.adoc[Восстановление карточки или ярлыка]* +

*На уровень выше:* xref:../topics/CardsArm.adoc[Работа с карточками]
