= Поля карточки

Поля карточки можно классифицировать двумя способами:

. По способу создания:
* базовые поля, которые присутствуют в базовых типах карточек системы _{dv}_;
* динамические поля, которые добавляются при внедрении системы {dv}.
. По способу хранения:
* поля, имеющие фиксированное значение, хранимое системой в виде строки данных;
* ссылочные поля, значение которых является ссылкой на другую карточку или на запись в справочнике;
* поля, которые в зависимости от способа заполнения могут как быть ссылочными, так и нет.

При наличии установленного приложения _Управление процессами_, поле ссылочного типа может ссылаться на объект шлюза.

Значение ссылочного поля физически не хранится в карточке и может быть выбрано из списка существующих значений. Изменения, произведенные в справочнике (например, изменение фамилии сотрудника в справочнике сотрудников), передаются в ссылочные поля карточки, зарегистрированной до изменения. Если поле ссылается на удаленный элемент справочника, то оно содержит надпись `Значение недоступно`.

К полям с фиксированным значением всегда относятся поля, хранящие значения типов целое число, дробное число, да/нет, дата/время, строка, перечисление. Даже если значение такого поля выбирается из справочника (например, номер, выданный нумератором), оно хранятся как зафиксированное. Значение полей второй группы, как правило, вводится вручную (поле *Реквизит* карточек документов), но может быть передано из справочника (поле *Телефон* окна *Получатели* карточки исходящего документа). В последнем случае переданное из справочника значение преобразуется в значение одного из перечисленных типов (в данном случае в целое). Изменения, произведенные в справочниках, не передаются в поля с фиксированным значением.

В дополнение к вышеперечисленным, существуют поля, значения которых в зависимости от способа ввода могут быть как ссылочными, так и фиксированными. Для хранения значений полей этой группы в карточке заведены два поля: одно для хранения ссылки, второе -- для хранения фиксированного значения; в зависимости от способа ввода значения (из справочника или вручную) заполняется одно из них. Примером такого поля является поле *Получатель* диалогового окна *Получатели* карточки исходящего документа, которое может выступать как в качестве ссылочного (если значение выбрано из справочника контрагентов), так и в качестве поля с фиксированным значением (если значение было введено в поле вручную и не синхронизировано со справочником).

Таким образом, при изменении в справочнике некоторого элемента, будут изменены все ссылающиеся на него значения в карточках, а поля, имеющие фиксированное значение, останутся неизменными.

Подобным поведением обусловлен в частности тот факт, что после удаления информации из справочника некоторые отрывочные сведения из нее иногда остаются в карточках. Например, при удалении некоторой организации из справочника контрагентов, в ссылающихся на нее поле *Организация* и свойстве типа *подразделение контрагента* карточки документа появится надпись <Значение недоступно>, но поля, содержащие подробные сведения о контрагенте (телефон, адрес, e-mail), сохранят свои значения.
