= Работа с карточками

_Карточка_ -- элемент системы {dv}, предназначенный для упорядоченного хранения сведений о внешних объектах и процессах, информация о которых является предметом учета, хранения и обработки. Карточки создаются пользователем при регистрации документа (или другого объекта, например, файла).

Для работы в системе _{dv} 5_ предназначены карточки, входящие в состав библиотеки _{bo}_.

.В справочнике видов карточек эти карточки представлены следующими базовыми типами:
* Документ.
* Задание.
* Группа заданий.
* Бизнес-календарь.
* Согласование.

Для каждого базового типа карточки может быть создано неограниченное число пользовательских видов (см. xref:backofficedesdirs:card-kinds/directory.adoc["Справочник видов карточек"]).

[NOTE]
====
{wincl} позволяет работать как с карточками _{dv} 5_, так и с карточками более ранних версий системы. Однако, в предыдущих версиях системы, настройка видов, разметок и состояний карточек выполняется другими инструментами.
====

_Ярлыком_ карточки называется ссылка на карточку, которую пользователь может разместить в любой папке.
