= Приложение B. Параметры запуска {wincl}а из командной строки

== Настройки {wincl}а

include::partial$appendix.adoc[tags=2048]
+
[NOTE]
====
Открыть _РМА_ можно только из адресной строки браузера. Из конфигурационного файла и командной строки открыть РМА невозможно.
====
+
* `SkipVersionCheck` -- выполнение проверки соответствия версии установленного решения и версии, запрошенной сервером:
** `true` -- не выполнять проверку.
** `false` -- выполнять проверку.
* `DisableVersionMismatchNotification` -- отключение отображения сообщения о несоответствии версий:
** `true` -- отключить.
** `false` -- не отключать.
* `IgnoreInvalidCert` -- при соединении по SSL, игнорировать некорректный сертификат сервера.
* `LogFile` -- путь к файлу с журналом {wincl}а.
* `PrecacheCards` -- включает предварительное кэширование компонент карточек при запуске {wincl}а:
** `true` (по умолчанию) -- предварительное кэширование включено.
** `false` -- предварительное кэширование отключение.
* `SynchronousPrecache` -- включает режим синхронного (по умолчанию -- асинхронный) предварительного кэширования компонент карточек:
** `true` -- включить режим синхронного предварительного кэширования.
** `false` (по умолчанию) -- отключить режим синхронного предварительного кэширования, будет использован асинхронный режим.
* `RecentDocumentsMaxCount` -- максимальное число хранящихся в папке _Последние_ ярлыков на карточки.
* `EnableVirtualizing` -- включает https://msdn.microsoft.com/ru-ru/library/system.windows.controls.virtualizationmode(v=vs.110).aspx[виртуализированный] режим работы панели {wincl}а с деревом папок:
** `true` (по умолчанию) -- включён.
** `false` -- отключен.

== Настройки соединения с сервером

include::partial$appendix.adoc[tags=disntlm]
+
** `true` -- не использовать встроенную аутентификацию.
** `false` -- использовать встроенную аутентификацию.
+
include::partial$appendix.adoc[tags=conn-address]
+
* `InitialPort` -- начальный порт (по умолчанию -- `8095`) для поиска запущенных экземпляров {wincl}а.
* `FinalPort` -- конечный порт (по умолчанию -- `8105`) для поиска запущенных экземпляров {wincl}а.

Перечисленные выше параметры могут быть указаны непосредственно в конфигурационном файле {wincl}а. В этом случае указывать их при запуске программы не нужно.

. Откройте файл `Каталог-установки-{wincl}а/Navigator.dll.config`.
. Добавьте требуемые параметры:
+
* Параметры `RecentDocumentsMaxCount` и `EnableVirtualizing` -- в элемент `configuration/{dv}.platform.wpf.navigator/navigator/folders`.
* Другие параметры -- в элемент `configuration/{dv}.platform.wpf.navigator/navigator/connection`
+
Следующий пример демонстрирует содержимое конфигурационного файла с добавленными параметрами `LogFile` и `EnableVirtualizing`.
+
[source]
----
<?xml version="1.0"?>
<configuration>
   <!-- Содержимое секции configSections -->

   <{dv}.platform.wpf.navigator>
      <navigator>
          <connection LogFile="C:/Logs/Windows_client.log"/>
          <folders EnableVirtualizing="True"/>
      </navigator>
   </{dv}.platform.wpf.navigator>
  
  <!-- Содержимое секций runtime и startup -->

</configuration>
----
+
.Обратите внимание на формат записи параметров:
[WARNING]
====
* Названия параметров являются регистрозависимыми.
* Значения параметров должны быть указаны в двойных кавычках.
====
+
. Сохраните изменения файла `Navigator.dll.config`, перезапустите {wincl}.
