= Использование клиентской сортировки при первом показе

Для оптимизации первичного открытия папки, содержащей большое количество карточек, пользовательские параметры сортировки могут быть отключены, а вместо них будет использоваться серверная сортировка данных представления. Настройка распространяется на папки типов _Стандартная_, _Виртуальная_, _Делегат_ (как на _Стандартную_, так и на _Виртуальную_ папку), а также на системные папки ([.keyword]*Корзина*, [.keyword]*Избранное*, [.keyword]*Результаты поиска*, [.keyword]*Последние*).

[NOTE]
====
Если сортировка определена в настройках представления, она будет использоваться во всех случаях.
====

Чтобы при первом открытии папки использовалась серверная сортировка, выполните следующие действия:

[[task_ojx_tbq_2q__steps_mpb_5cq_2q]]
. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки, затем нажмите на кнопку [.keyword]*Другие*.#
. [.ph .cmd]#Установите флаг *Необходимость применения клиентской сортировки при первом показе*.#
+
По умолчанию флаг не установлен.
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*ОК*.#
+
При первом открытии папки данные будут показываться в том порядке, которые предоставил сервер. При повторном открытии папки будут применены методы сортировки, настроенные пользователем.

[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.#
