= Копирование ветки дерева папок

Ветку дерева папок (пользовательскую папку вместе со всеми дочерними папками всех уровней) можно скопировать в другую папку, не принадлежащую этой ветке; ветка дерева копируется с охранением структуры папок. Все папки копируются вместе с настройками, то есть все свойства скопированных папок сохраняют оригинальные значения. Карточки в скопированных папках заменяются ярлыками карточек.

Если название верхней папки копируемой ветки совпадает с названием уже имеющейся в папке назначения подпапки, копии будет присвоено то же название, но с номером (1); при повторном копировании нумерация будет продолжена.

[NOTE]
====
Производящий копирование ветки дерева папок пользователь должен иметь права на чтение и изменение всех папок этой ветки.
====

Для копирования папки выполните одно из следующих действий:

[[task_v51_3hh_nn__steps_esk_jhh_nn]]
. [.ph .cmd]#Выберите команду контекстного меню [.ph .uicontrol]*Скопировать структуру папок*. #
. [.ph .cmd]#Выберите из главного меню последовательно [.ph .menucascade]#[.ph .uicontrol]*Файл* > [.ph .uicontrol]*Папка* > [.ph .uicontrol]*Скопировать структуру папок*#. #
