[[ariaid-title1]]
== Просмотр содержимого папки

Содержимое папки может отображаться в xref:Interface_view_area.html[[.dfn .term]_Области представления_] следующими способами:

* как таблица, столбцы которой представляют собой названия полей карточек, а строки отражают информацию, содержащуюся в соответствующих полях карточек.
+
[NOTE]
====
[.note__title]#Прим.:# Выбор полей карточек, которые будут отображаться в представлении, как правило, определяются при внедрении системы Docsvision на основании пожеланий заказчика.
====
* как xref:Folder_url.adoc[веб-страница], находящаяся по определенному адресу;
* как определенная открытая xref:Folder_card.adoc[карточка].

Для просмотра содержимого папки выполните следующие действия:

[[task_wmg_hnm_wn__steps_iqb_jnm_wn]]
[.ph .cmd]#Выберите в xref:Interface_folder_tree.adoc[Дереве папок] название папки, содержимое которой требуется просмотреть. #

В xref:Interface_view_area.adoc[Области представления] будет отображен список карточек и/или ярлыков, которые в ней находятся. Состав представления при этом зависит от прав текущего пользователя в системе.

*На уровень выше:* xref:../topics/Folders.adoc[Работа с папками]
