= Использование клиентской сортировки при первом показе

Для оптимизации первичного открытия папки, содержащей большое количество карточек, пользовательские параметры сортировки могут быть отключены, а вместо них будет использоваться серверная сортировка данных представления. Настройка распространяется на папки типов _Стандартная_, _Виртуальная_, _Делегат_ (как на _Стандартную_, так и на _Виртуальную_ папку), а также на системные папки (*Корзина*, *Избранное*, *Результаты поиска*, *Последние*).

[NOTE]
====
Если сортировка определена в настройках представления, она будет использоваться во всех случаях.
====

Чтобы при первом открытии папки использовалась серверная сортировка, выполните следующие действия:. xref:Folder_properties.adoc[Откройте] окно свойств папки, затем нажмите на кнопку *Другие*.
. Установите флаг *Необходимость применения клиентской сортировки при первом показе*.
+
По умолчанию флаг не установлен.
. Нажмите на кнопку *ОК*.
+
При первом открытии папки данные будут показываться в том порядке, которые предоставил сервер. При повторном открытии папки будут применены методы сортировки, настроенные пользователем.

Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.
