= Просмотр содержимого папки

Содержимое папки может отображаться в xref:Interface-view-area[_Области представления_] следующими способами:

* как таблица, столбцы которой представляют собой названия полей карточек, а строки отражают информацию, содержащуюся в соответствующих полях карточек.
+
[NOTE]
====
Выбор полей карточек, которые будут отображаться в представлении, как правило, определяются при внедрении системы {dv} на основании пожеланий заказчика.
====
* как xref:Folder_url.adoc[веб-страница], находящаяся по определенному адресу;
* как определенная открытая xref:Folder_card.adoc[карточка].

Для просмотра содержимого папки выполните следующие действия:Выберите в "xref:interface-navigation-area.adoc#tree[Дереве папок]" название папки, содержимое которой требуется просмотреть.

В xref:interface-view-area.adoc[Области представления] будет отображен список карточек и/или ярлыков, которые в ней находятся. Состав представления при этом зависит от прав текущего пользователя в системе.
