= Обновление представления папки

Для представления папки можно настроить требуемый режим обновления. По умолчанию при переходе в папку выполняется автоматическое обновление представления. Однако, при необходимости данный режим может быть изменен.

Пользователь может либо отключить автоматическое обновление, либо указать требуемый период обновления. По умолчанию период обновления папки составляет `300` секунд.

Можно изменить этот параметр: отключить автоматическое обновление вообще, либо самостоятельно указать период, выбрав и настроив пункт _Специальное_.

.Чтобы настроить режим обновления представления папки, выполните следующие действия:
. xref:folder-properties.adoc[Откройте] окно свойств папки, затем нажмите на кнопку *Другие*.
. Установите флаг `*Разрешить обновление при переходе в папку*`, чтобы представление папки обновлялось автоматически при открытии папки.
+
По умолчанию флаг установлен. Если автоматическое обновление отключено, содержимое папки можно обновить вручную с помощью кнопки *Обновить* на ленте {wincl}а.
+
. Чтобы отключить автоматическое обновление представления папки, выберите опцию *Выключено*.
. Чтобы использовать стандартный интервал обновления представления (`300` секунд), выберите опцию *Стандартное*.
. Чтобы использовать другой интервал обновления представления, выберите опцию *Специальное*, затем настройте нужный интервал в соседнем поле.
. Нажмите на кнопку *ОК*.
+
include::partial$excerpts.adoc[tags=after-refresh]
