= Просмотр содержимого папки

Содержимое папки может отображаться на правой панели окна _РМА_ одним из трех способов:

* список карточек в виде таблицы (представление), заголовки которой представляют собой названия полей карточек, а строки отражают информацию, содержащуюся в соответствующих полях карточек; выбор полей карточек, которые будут отображаться в представлении, зависит от потребностей и пожеланий конкретного пользователя;
+
[NOTE]
====
При большом количестве отображаемых полей и малом количестве карточек можно задать инверсное отображение таблицы, так чтобы названиям полей карточек соответствовали названия строк.
====
* веб-страница, находящаяся по указанному веб-адресу;
* одна из карточек, находящихся в папке.

Способ отображения содержимого папки указывается в окне свойств папки, которое можно открыть, нажав в меню menu:*Файл* > *Папка* > *Свойства* или выбрав из контекстного меню команду *Свойства*. В открывшемся окне в разделе *Отображать по умолчанию* следует выбрать нужный переключатель (*Папку*, *Карточку* или *URL*), причем:

* если переключатель находится в положении *Папка*, можно выбрать представление, в котором будет выводиться содержимое папки (по умолчанию это представление _Дайджест_);
* если переключатель находится в положении *Карточка*, необходимо выбрать карточку, которая будет отображаться в области просмотра, при этом карточка не обязательно должна находиться в данной папке;
* если переключатель находится в положении *URL*, то можно указать адрес веб-страницы, которая по умолчанию будет отображаться в области просмотра; если адрес не указан, область просмотра останется пустой.

[NOTE]
====
Если переключатель находится в положении *URL*, то в качестве содержимого папки {dv} можно указать папку файловой системы. Это облегчит копирование файлов между файловой системой и {dv}.
====

Приведенное в настоящем документе описание действий с папками касается только папок, содержимое которых отображается в виде представления.

При просмотре содержимого папки может использоваться следующий инструментарий представления данных:

* xref:Description_Area_View_Folder_Contents.adoc[организация постраничного просмотра] при большом количестве данных в папке;
* смена представлений;
* xref:Folders_Sorting_Data.adoc[сортировка данных];
* xref:Views_Grouping_Data_Representation.adoc[группировка данных];
* автоматическая фильтрация данных представления;
* сохранение и отмена пользовательских настроек.

* *xref:../topics/Folders_Change_of_View.adoc[Смена представления]* +
* *xref:../topics/Folders_Data_Filtering.adoc[Автоматическая фильтрация данных]* +
* *xref:../topics/Folders_SavingCancellation_User_Settings.adoc[Сохранение и отмена пользовательских настроек]* +
