= Локализация названия папки

Система {dv} поддерживает возможность использования локализованных названий папок -- отображаемое название папки зависит от текущего языка интерфейса {wincl}а.

Возможность локализации названий папок по умолчанию отключена. Для её активации администратор {dv} должен включить поддержку локализации значений полей следуя инструкции, приведённой в Руководстве администратора модуля {pl}, пункт "Настройка режима локализации полей".

Для установки локализованного названия папки:

. xref:settings-general.adoc#language[Выберите язык интерфейса {wincl}], для которого нужно установите название папки.
. Выберите команду *Переименовать* в контекстном меню папки и откройте xref:Folder_properties.adoc[панель настройки свойств папки].
. Введите новое название папки для языка интерфейса, с которым открыт {wincl}.
. Примените изменения.
+
Обратите внимание: при установке названия папки для языка локализации, не являющегося языком локализации по умолчанию, проверка существования папки с аналогичным названием не выполняется. Т. е. возможна ситуация, при которой в родительской папке будут существовать несколько папок с идентичным названием.

При отображении папок, используются названия, установленные для текущего языка интерфейса {wincl}а. Если название папки для данного языка не установлено, будет использовано название установленное для языка локализации по умолчанию. Язык по умолчанию устанавливается администратором {dv}.
