= Ограничение количества выводимых записей

По умолчанию, на одной странице представления папки отображается 40 записей. Если записей больше, для просмотра следует использовать кнопки перехода между страницами. При необходимости, количество выводимых записей на странице можно изменить.

Чтобы ограничить количество отображаемых карточек/ярлыков на странице, выполните следующие действия:

. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки, затем нажмите на кнопку [.keyword]*Другие*.#
. [.ph .cmd]#Чтобы ввести ограничение на количество выводимых записей, установите флаг *Ограничение количества выводимых записей*.#
. [.ph .cmd]#в поле справа укажите максимальное количество записей для просмотра.#
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*ОК*.#
+
[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.#
