= Ограничение на использование типов карточек для папки

По умолчанию, в папке могут быть созданы карточки любых типов и видов из числа доступных в _Справочнике видов карточек_. Однако, при необходимости набор типов/видов для создаваемых карточек в папке может быть ограничен.

Чтобы ввести ограничение на создание карточек определенных видов, выполните следующие действия:

. xref:Folder_properties.adoc[Откройте] окно свойств папки, затем перейдите на вкладку *Типы*.
. Чтобы включить ограничение на использование типов/видов карточек, установите флаг *Только эти типы карточек могут быть созданы в этой папке*.
. Сформируйте список допустимых типов/видов карточек: установите флаги напротив допустимых видов и снимите флаги напротив запрещенных видов. Для выбора всех записей воспользуйтесь кнопками *Выделить все* и *Снять все отметки*.
. Примените изменения кнопками *Применить* или *ОК*.
+
Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.
