[[ariaid-title1]]
== Шаблон для экспорта папки в Excel

Шаблон экспорта папки необходим при выполнении экспорта представления папки в формат MS Excel. При необходимости, набор доступных шаблонов экспорта может быть xref:Folder_template_list.adoc[ограничен].

По умолчанию, для папки применяется [.keyword .parmname]_Пустой шаблон_, когда экспорт производится без каких-либо настроек.

Чтобы изменить шаблон экспорта, используемый по умолчанию, выполните следующие действия:

. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки.#
. [.ph .cmd]#Найдите поле [.keyword]*Шаблон*. #
. [.ph .cmd]#Выберите из списка один из заранее настроенных шаблонов. #
+
Для папки типа [.dfn .term]_Делегат_ в списке будут доступны шаблоны, разрешенные для делегирующей папки.
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*ОК*.#
+
[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска [.dfn .term]_Windows-клиента_ или обновления дерева папок.#

*На уровень выше:* xref:../topics/Folder_properties.adoc[Настройка свойств папки]
