[[ariaid-title1]]
== Обновление представления папки

Для представления папки можно настроить требуемый режим обновления. По умолчанию, при переходе в папку выполняется автоматическое обновление представления. Однако, при необходимости, данный режим может быть изменен. Пользователь может либо отключить автоматическое обновление, либо указать требуемый период обновления. По умолчанию, период обновления папки составляет 300 секунд.

Имеется возможность изменить этот параметр: отключить автоматическое обновление вообще, либо самостоятельно указать период, выбрав и настроив пункт *Специальное*.

Чтобы настроить режим обновления представления папки, выполните следующие действия:

. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки, затем нажмите на кнопку [.keyword]*Другие*.#
. [.ph .cmd]#Чтобы представление папки обновлялось автоматически при открытии папки, установите флаг *Разрешить обновление при переходе в папку*.#
+
По умолчанию флаг установлен. При отключенном автоматическом обновлении возможность вручную обновить содержимое папки сохраняется (с помощью кнопки *Обновить* на ленте Windows-клиента).
. [.ph .cmd]#Чтобы отключить автоматическое обновление представления папки, выберите опцию [.keyword]*Выключено*.#
. [.ph .cmd]#Чтобы использовать стандартный интервал обновления представления (300 секунд), выберите опцию [.keyword]*Стандартное*.#
. [.ph .cmd]#Чтобы использовать другой интервал обновления представления, выберите опцию [.keyword]*Специальное*, затем настройте нужный интервал в соседнем поле.#
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*ОК*.#
+
[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска [.dfn .term]_Windows-клиента_ или обновления дерева папок.#

*На уровень выше:* xref:../topics/Folder_properties.adoc[Настройка свойств папки]
