[[ariaid-title1]]
== Ограничение на использование типов карточек для папки

По умолчанию, в папке могут быть созданы карточки любых типов и видов из числа доступных в [.dfn .term]_Справочнике видов карточек_. Однако, при необходимости, набор типов/видов для создаваемых карточек в папке может быть ограничен.

Чтобы ввести ограничение на создание карточек определенных видов, выполните следующие действия:

. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки, затем перейдите на вкладку [.keyword]*Типы*.#
. [.ph .cmd]#Чтобы включить ограничение на использование типов/видов карточек, установите флаг [.keyword]*Только эти типы карточек могут быть созданы в этой папке*.#
. [.ph .cmd]#Сформируйте список допустимых типов/видов карточек: установите флаги напротив допустимых видов и снимите флаги напротив запрещенных видов. Для выбора всех записей воспользуйтесь кнопками [.keyword]*Выделить все* и [.keyword]*Снять все отметки*.#
. [.ph .cmd]#Примените изменения кнопками [.keyword]*Применить* или [.keyword]*ОК*.#
+
[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска [.dfn .term]_Windows-клиента_ или обновления дерева папок.#

*На уровень выше:* xref:../topics/Folder_properties.adoc[Настройка свойств папки]
