= Проверка прав доступа в представлениях

По умолчанию при получении списка карточек в папке (для формирования представления), сервер {dv} предварительно проверяет права пользователя на все карточки данной папки. Если в папке большое количество карточек, процесс получения списка карточек может занять продолжительное время. Альтернативное поведение: не проверять права на карточки папки (при этом пользователь по-прежнему не сможет открывать недоступные ему карточки) или проверять права только на карточки загружаемой страницы представления (по мере необходимости).

Чтобы выбрать вариант проверки прав доступа в представлении папки, выполните следующие действия:

. xref:Folder_properties.adoc[Откройте] окно свойств папки, затем нажмите на кнопку *Другие*.
. Измените значение переключателя в блоке настроек *Проверка прав доступа в представлениях*:
* "Все карточки" (поведение по умолчанию) -- на сервере формируется список доступных пользователю карточек текущей папки, клиенту передается одна страница полученного списка;
* "Постранично" -- на сервере формируется список всех карточек текущей папки, клиенту передается одна страница со списком доступных пользователю карточек, в фоне клиент постепенно получает с сервера другие страницы;
+
При постраничном режиме проверки прав доступа пользователям будет недоступно точное количество карточек папки, а также точное количество страниц в представлении, пока все страницы не будут загружены. При этом справа от количества загруженных карточек/страниц будет отображаться символ "+", указывающий на наличие незагруженных карточек/папок.
+
*В РМА символ "+", сигнализирующий о наличии незагруженных карточек/страниц представления, не отображается.*
* "Отключить" -- на сервере формируется список всех карточек текущей папки, клиенту передается одна страница полученного списка.
+
Данный режим проверки прав доступа недоступен для виртуальных папок.
+
[NOTE]
====
[.note__title]Important: Если проверка прав доступа отключена, пользователю будут показаны все карточки папки, в т.ч. недоступные. Открыть карточку, к которой нет доступа, пользователь не сможет: появится сообщение об отсутствии прав.
====
. Нажмите на кнопку *ОК*.

[NOTE]
====
[.note__title]Important: В папках с режимом проверки прав доступа "Постранично" и "Отключить" непрочитанные карточки не выделяются (жирным шрифтом), количество непрочитанных карточек не отображается.
====
