= Показывать по умолчанию

Для папки может быть настроено несколько вариантов отображения. Например, в свойствах папки могут быть одновременно настроены xref:Folder_url.adoc[ссылка], xref:Folder_card.adoc[карточка папки] и xref:Folder_view.adoc[представление]. Для определения предпочтительного режима работы с папкой используется переключатель [.keyword]*Показывать по умолчанию*.

Опция переключателя доступна только при заполнении поля, соответствующего режиму отображения:

* папку (опция используется по умолчанию);
* карточку;
* URL.

Чтобы настроить режим показа содержимого папки, выполните следующие действия:

[[task_it1_5sm_wn__steps_l5n_jsm_wn]]
. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки.#
. [.ph .cmd]#Для настройки режима показа карточки, выполните: #
[loweralpha]
.. [.ph .cmd]#Заполните поле xref:Folder_card.adoc[Карточка папки].#
.. [.ph .cmd]#Установите переключатель [.keyword]*Показывать по умолчанию* в положение [.keyword]*Карточку*.#
. [.ph .cmd]#Для настройки режима показа веб-страницы, выполните:#
[loweralpha]
.. [.ph .cmd]#Заполните поле xref:Folder_url.adoc[Ссылка].#
.. [.ph .cmd]#Установите переключатель [.keyword]*Показывать по умолчанию* в положение [.keyword]*URL*.#
. [.ph .cmd]#Для настройки режима показа представления, выполните:#
[loweralpha]
.. [.ph .cmd]#Заполните поле xref:Folder_view.adoc[Представление].#
.. [.ph .cmd]#Установите переключатель [.keyword]*Показывать по умолчанию* в положение [.keyword]*Представление*.#
+
[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.#
