= Ограничение на использование шаблонов для папки

По умолчанию, для экспорта представления папки в формат MS Excel могут использоваться любые шаблоны. Однако, при необходимости, набор доступных шаблонов может быть ограничен.

Шаблон, который будет использоваться для экспорта по умолчанию, xref:Folder_template.adoc[настраивается] в общих параметрах папки.

Чтобы ввести ограничение на использование шаблонов экспорта представления, выполните следующие действия:


. xref:Folder_properties.adoc[Откройте] окно свойств папки, затем перейдите на вкладку *Типы*.
. Чтобы включить ограничение на использование шаблонов, установите флаг *Только эти шаблоны могут быть использованы в этой папке* .
. Сформируйте список допустимых шаблонов: установите флаги напротив допустимых видов и снимите флаги напротив запрещенных видов. Для выбора всех записей воспользуйтесь кнопками *Выделить все* и *Снять все отметки*.
. Примените изменения кнопками *Применить* или *ОК*.
+
Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.
