= Ограничение на использование шаблонов для папки

По умолчанию, для экспорта представления папки в формат MS Excel могут использоваться любые шаблоны. Однако, при необходимости, набор доступных шаблонов может быть ограничен.

Шаблон, который будет использоваться для экспорта по умолчанию, xref:Folder_template.adoc[настраивается] в общих параметрах папки.

Чтобы ввести ограничение на использование шаблонов экспорта представления, выполните следующие действия:

[[task_lkf_wjd_yn__steps_a4t_tkd_yn]]
. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки, затем перейдите на вкладку [.keyword]*Типы*.#
. [.ph .cmd]#Чтобы включить ограничение на использование шаблонов, установите флаг [.keyword]*Только эти шаблоны могут быть использованы в этой папке* .#
. [.ph .cmd]#Сформируйте список допустимых шаблонов: установите флаги напротив допустимых видов и снимите флаги напротив запрещенных видов. Для выбора всех записей воспользуйтесь кнопками [.keyword]*Выделить все* и [.keyword]*Снять все отметки*.#
. [.ph .cmd]#Примените изменения кнопками [.keyword]*Применить* или [.keyword]*ОК*.#
+
[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.#
