= Ограничение на использование представлений для папки

По умолчанию, для папки могут использоваться любые созданные администратором представления. Однако, при необходимости, набор доступных представлений может быть ограничен.

Представление, которое будет использоваться для папки по умолчанию, xref:Folder_view.adoc[настраивается] в общих параметрах папки.

Чтобы ограничить список представлений, которые могут использоваться для папки, выполните следующие действия:

. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки, затем перейдите на вкладку [.keyword]*Представления*.#
. [.ph .cmd]#Чтобы включить ограничение на использование представлений, установите флаг [.keyword]*Только эти представления могут быть показаны в этой папке*.#
. [.ph .cmd]#Сформируйте список допустимых представлений: установите флаги напротив допустимых представлений и снимите флаги напротив запрещенных представлений. Для выбора всех записей воспользуйтесь кнопками [.keyword]*Выделить все* и [.keyword]*Снять все отметки*.#
. [.ph .cmd]#Примените изменения кнопками [.keyword]*Применить* или [.keyword]*ОК*.#
+
[.ph]#Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.#
