= Автоматическое применение фильтра виртуальной папки к карточке, после её изменения

По умолчанию, если у пользователя открыта виртуальная папка и карточка в ней была изменена, фильтр папки повторно (к карточке) не применяется, из-за чего в виртуальной папке может отображаться (до обновления содержимого папки) карточка, данные которой после изменения перестали удовлетворять фильтру этой папки.

Чтобы включить автоматическое скрытие карточек, данные которых не удовлетворяют фильтру виртуальной папки, выполните следующие действия:

. xref:folder-properties.adoc[Откройте] окно свойств папки, затем нажмите на кнопку *Другие*.
. Установите флаг *Скрывать карточку, не удовлетворяющую фильтру, сразу после её изменения*.
+
По умолчанию флаг не установлен.

[IMPORTANT]
====
Флаг отображается в настройках только виртуальных папок и только в {wincl}е. В РМА флаг не отображается, функция автоматического применения фильтра не работает.
====
. Нажмите на кнопку *ОК*.
+
include::partial$excerpts.adoc[tags=after-refresh]
