= Локализация названия папки

Система {dv} поддерживает возможность использования локализованных названий папок -- отображаемое название папки зависит от текущего языка интерфейса {wincl}а.

Возможность локализации названий папок по умолчанию отключена. Для её активации администратор {dv} должен включить поддержку локализации значений полей, следуя инструкции, xref:dev@platform:console:default-localization.adoc[приведённой] в документации по администрированию модуля платформа.

.Чтобы установить локализованное название папки:
. xref:settings-general.adoc#language[Выберите язык интерфейса {wincl}а], для которого нужно установить название папки.
. Выберите команду _Переименовать_ в контекстном меню папки и откройте xref:folders-properties.adoc[панель настройки свойств папки].
. Введите новое название папки для языка интерфейса, с которым открыт {wincl}.
. Примените изменения.
+
[WARNING]
====
Поиск папки с таким же названием выполняется только для языка локализации по умолчанию. Для других языков проверка не выполняется. Т. е. возможна ситуация, при которой в родительской папке будут существовать несколько папок с идентичным названием.
====
+
При отображении папок, используются названия, установленные для текущего языка интерфейса {wincl}а. Если название папки для данного языка не установлено, будет использовано название установленное для языка локализации по умолчанию. Язык по умолчанию устанавливается администратором {dv}.
