[[ariaid-title1]]
== Перемещение папки

Папку можно переместить в любую другую папку, не являющейся по отношению к ней дочерней. При этом папка со всеми содержащимися в ней данными удаляется оттуда, где она находилась ранее, и копируется в выбранную папку.

Для перемещения папки выполните одно из следующих действий:

. [.ph .cmd]#Выберите команду контекстного меню [.ph .uicontrol]*Переместить папку*.#
. [.ph .cmd]#Выберите из главного меню [.ph .menucascade]#[.ph .uicontrol]*Файл* > [.ph .uicontrol]*Папка* > [.ph .uicontrol]*Переместить папку*#. #
. [.ph .cmd]#Щелкните по перемещаемой папке и, удерживая левую кнопку мыши нажатой, перетащите ее в нужную папку. При использовании этого способа на экран выводится сообщение: `Вы уверены, что хотите переместить папку "<Название                         папки>" в папку "<Название папки>"?`, после чего пользователь может подтвердить или отменить перемещение. #
+
[NOTE]
====
[.note__title]#Прим.:# Если пользователь установит в окне полученного сообщения флаг [.ph .uicontrol]*Не выводить больше это сообщение*, в дальнейшем сообщение на экран выводиться не будет; восстановить получение сообщения нельзя.
====

*На уровень выше:* xref:../topics/Folders_Actions_with_Folders.adoc[Действия с папками]
