= Ограничение на использование представлений для папки

По умолчанию, для папки могут использоваться любые созданные администратором представления. Однако, при необходимости набор доступных представлений может быть ограничен.

Представление, которое будет использоваться для папки по умолчанию, xref:folder-view.adoc[настраивается] в общих параметрах папки.

Чтобы ограничить список представлений, которые могут использоваться для папки, выполните следующие действия:

. xref:folder-properties.adoc[Откройте] окно свойств папки, затем перейдите на вкладку *Представления*.
. Чтобы включить ограничение на использование представлений, установите флаг *Только эти представления могут быть показаны в этой папке*.
. Сформируйте список допустимых представлений: установите флаги напротив допустимых представлений и снимите флаги напротив запрещенных представлений. Для выбора всех записей воспользуйтесь кнопками *Выделить все* и *Снять все отметки*.
. Примените изменения кнопками *Применить* или *ОК*.
+
include::partial$excerpts.adoc[tags=after-refresh]
