= Оптимизация загрузки представления

Оптимизация загрузки представления заключается в превентивной подготовке данных, необходимых для формирования представления папки. Подготовка данных осуществляется периодически выполняемой SQL-задачей.

Оптимизация применяется только при работе с представлением, xref:Folder_view.adoc[выбранным в настройках папки], и не применима к виртуальным папкам с параметрическим поисковым запросом.

[NOTE]
====
[.note__title]#Important:# Включать оптимизацию рекомендуется только для папок, содержащих неизменяемый или редко изменяемый набор карточек (например, архив карточек). Если оптимизация включена для папки с часто изменяемыми карточками, данные в представлении могут обновляться с задержкой (до 5 минут).
====

. [.ph .cmd]#xref:Folder_properties.adoc[Откройте] окно свойств папки.#
. [.ph .cmd]#Установите флаг [.ph .uicontrol]*Оптимизировать загрузку представления по умолчанию*.#
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*ОК*.#
+
Оптимизация загрузки представления заработает в течение 5 минут.

*Parent topic:* xref:../topics/Folder_properties.adoc[Настройка свойств папки]
