= Показывать по умолчанию

Для папки может быть настроено несколько вариантов отображения. Например, в свойствах папки могут быть одновременно настроены xref:Folder_url.adoc[ссылка], xref:Folder_card.adoc[карточка папки] и xref:Folder_view.adoc[представление]. Для определения предпочтительного режима работы с папкой используется переключатель *Показывать по умолчанию*.

Опция переключателя доступна только при заполнении поля, соответствующего режиму отображения:

* папку (опция используется по умолчанию);
* карточку;
* URL.

Чтобы настроить режим показа содержимого папки, выполните следующие действия:


. xref:Folder_properties.adoc[Откройте] окно свойств папки.
. Для настройки режима показа карточки, выполните:
[loweralpha]
.. Заполните поле xref:Folder_card.adoc[Карточка папки].
.. Установите переключатель *Показывать по умолчанию* в положение *Карточку*.
. Для настройки режима показа веб-страницы, выполните:
[loweralpha]
.. Заполните поле xref:Folder_url.adoc[Ссылка].
.. Установите переключатель *Показывать по умолчанию* в положение *URL*.
. Для настройки режима показа представления, выполните:
[loweralpha]
.. Заполните поле xref:Folder_view.adoc[Представление].
.. Установите переключатель *Показывать по умолчанию* в положение *Представление*.
+
Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_ или обновления дерева папок.
