= Просмотр журнала сообщений

Для просмотра сообщений нужного журнала ([.keyword]*Журнала сообщений*, [.keyword]*Системного журнала*, [.keyword]*Журнала безопасности*) следует выделить его в левой панели окна xref:Logs_Navigator_Log_Window.html#concept_ybl_tkd_hp__image_vs1_nmd_hp[[.keyword .wintitle]*Журнал*], при этом данные о зафиксированных операциях отобразятся в правой верхней панели данного окна.

Информация об операциях представлена в журнале в виде таблицы, в колонках которой отображается следующая информация:

* фамилия и инициалы пользователя, обратившегося к _{dv}_;
* его учетная запись (последняя колонка таблицы);
* сетевое имя компьютера, на котором открыта сессия пользователя;
* дата и время обращения к _{dv}_;
* выполненная пользователем операция;
* код операции;
* название элемента, над которым выполнялась операция.

Для удобства просмотра информации ее можно фильтровать нужным образом, выводя на экран только необходимые данные, а также просматривать подробности каждой выполненной пользователями операции.

Подробности любого сообщения каждого журнала можно просмотреть в поле [.ph .uicontrol]*Основная информация*; для этого следует просто выделить в таблице строку нужного сообщения.
