= Просмотр журнала сообщений

Чтобы просмотреть сообщения нужного журнала (_Журнала сообщений_, _Системного журнала_, _Журнала безопасности_), следует выделить его в левой панели окна xref:logs-window.adoc["Журнал"]. При этом данные о зафиксированных операциях отобразятся в правой верхней панели данного окна.

Информация об операциях представлена в журнале в виде таблицы, в колонках которой отображается следующая информация:

* Фамилия и инициалы пользователя, обратившегося к {dv}.
* Учетная запись пользователя -- последняя колонка таблицы.
* Сетевое имя компьютера, на котором открыта сессия пользователя.
* Дата и время обращения к {dv}.
* Выполненная пользователем операция.
* Код операции.
* Название элемента, над которым выполнялась операция.

Для удобства просмотра информации её можно фильтровать нужным образом, выводя на экран только необходимые данные, а также просматривать подробности каждой выполненной пользователями операции.

Подробности любого сообщения каждого журнала можно просмотреть в поле _Основная информация_. Для этого следует просто выделить в таблице строку нужного сообщения.
