= Очистка и удаление журнала

[#clear]
== Очистка журнала

Очистка журнала РМА от "лишних" записей производится только автоматически согласно настройкам, сделанным в ветке _Настройки журнала_ справочника _Системные настройки_.

При этом следует иметь в виду, что при очистке журнала записи удаляются без возможности восстановления. Если очистку не проводить, то размер базы данных {dv} со временем существенно увеличивается.

Поэтому, если необходимо хранить записи журнала за длительный период, в настройках базы данных {dv} должна быть xref:6.1@platform:console:archive-logs.adoc[указана] _Папка для резервных копий журнала_.

[NOTE]
====
Если в ветке `Server` реестра Windows указан ключ `IncludeStackTraceInLog` типа `DWORD` со значением `1`, в журнал будет добавляться последовательность вызовов.
====

[#delete]
== Удаление импортированного журнала

В системе предусмотрена операция удаления журналов, которые были xref:logs-export-import.adoc#import[импортированы] в систему. Функция используется для возврата к режиму просмотра собственных журналов.

Команда доступна только при наличии импортированных журналов. Удаления собственных журналов в системе не предусмотрено.

.Чтобы удалить импортированный журнал:
. Откройте xref:logs-window.adoc[Журнал сообщений РМА], выбрав в главном меню _РМА_ команду menu:Сервис[Журнал].
. Выберите в главном меню команду menu:Правка[Удалить журнал].
