[[ariaid-title1]]
== Журналы сообщений

Журнал сообщений предназначен для сбора сведений о действиях пользователей в системе Docsvision.

Журнал состоит из трех независимых журналов, в каждом из которых протоколируются операции соответствующих типов:

* Журнал безопасности;
* Системный журнал;
* Журнал приложений.

Пользователь, обладающий правами администратора, может просмотреть эти журналы, выбрав в главном меню программы РМА команду [.ph .menucascade]#[.ph .uicontrol]*Сервис* > [.ph .uicontrol]*Журнал*#. См. также xref:Logs_Navigator_View_Log.adoc[Просмотр журнала сообщений].

Журнал сообщений не допускает редактирования: его данные не могут быть модифицированы или удалены никаким пользователем. Удаление записей журнала производится только автоматически согласно настройкам, выполненным в справочнике [.dfn .term]_Системные настройки_ (см. xref:Logs_Navigator_Clear_History.adoc[Очистка журнала]).

Перемещение данных системного журнала допускается только в процессе реорганизации либо резервного копирования, причем его содержание остается неизменным.

* *xref:../topics/Logs_Navigator_Log_Window.adoc[Окно журнала сообщений]* +
* *xref:../topics/Logs_Navigator_View_Log.adoc[Просмотр журнала сообщений]* +
* *xref:../topics/Logs_Navigator_Filtering_Log_Data.adoc[Фильтрация данных журнала]* +
* *xref:../topics/Logs_Navigator_Export_Log_Messages.adoc[Экспорт сообщений журнала]* +
* *xref:../topics/Logs_Navigator_Import_Log_Messages.adoc[Импорт сообщений журнала]* +
* *xref:../topics/Logs_Navigator_Clear_History.adoc[Очистка журнала]* +
* *xref:../topics/Logs_Navigator_Deleting_an_Imported_Log.adoc[Удаление импортированного журнала]* +

*На уровень выше:* xref:../topics/Operations_rma.adoc[Описание операций в РМА]
