= Просмотр журнала сообщений

Для просмотра сообщений нужного журнала (*Журнала сообщений*, *Системного журнала*, *Журнала безопасности*) следует выделить его в левой панели окна xref:Logs_Navigator_Log_Window.adoc[*Журнал*], при этом данные о зафиксированных операциях отобразятся в правой верхней панели данного окна.

Информация об операциях представлена в журнале в виде таблицы, в колонках которой отображается следующая информация:

* фамилия и инициалы пользователя, обратившегося к {dv};
* его учетная запись (последняя колонка таблицы);
* сетевое имя компьютера, на котором открыта сессия пользователя;
* дата и время обращения к {dv};
* выполненная пользователем операция;
* код операции;
* название элемента, над которым выполнялась операция.

Для удобства просмотра информации её можно фильтровать нужным образом, выводя на экран только необходимые данные, а также просматривать подробности каждой выполненной пользователями операции.

Подробности любого сообщения каждого журнала можно просмотреть в поле *Основная информация*; для этого следует просто выделить в таблице строку нужного сообщения.
