[[ariaid-title1]]
== Очистка журнала

Очистка журнала РМА от «лишних» записей производится только автоматически согласно настройкам, сделанным в справочнике [.dfn .term]_Системные настройки_ в ветке [.keyword]*Настройки журнала*. При этом следует иметь ввиду, что при очистке журнала его записи удаляются без возможности восстановления, а если очистку не проводить, то размер базы данных [.dfn .term]_Docsvision_ со временем существенно увеличивается. Поэтому, если необходимо хранить записи журнала за длительный период, в настройках базы данных Docsvision должна быть указана [.ph .uicontrol]*Папка для резервных копий журнала* (документ [.ph]#[.dfn .term]_Модуль «Docsvision 5. Платформа». Руководство администратора_#, пункт «Настройка базы данных»).

[NOTE]
====
[.note__title]#Прим.:# При указании ключа [.dfn .term]_IncludeStackTraceInLog_ типа DWORD со значением [.kbd .ph .userinput]`1` в ветке [.keyword]*Server* реестра Windows в журнал будет добавляться последовательность вызовов.
====

*На уровень выше:* xref:../topics/Logs_Navigator.adoc[Журналы сообщений]
