= Управление блокировкой карточек и файлов

_Блокировкой_ называется состояние карточки _{dv}_ (карточки документа, карточки файла, справочника и т. д.), при котором она открыта для редактирования одним из сотрудников и доступна только для просмотра для всех остальных пользователей.

Все элементы, за исключением файлов, блокируются временно, на период редактирования. Снятие блокировки (разблокировка) элемента происходит при его закрытии редактирующим пользователем или администратором в принудительном порядке.

Файлы, прикрепленные к карточке документа, могут блокироваться как временно, что происходит при открытии их пользователями, так и постоянно, при выборе из контекстного меню опции [.ph .uicontrol]*Заблокировать*.

Администратор может просмотреть список всех заблокированных элементов системы, а также принудительно снять блокировку элемента, открытого кем-либо из пользователей для редактирования.

При аварийном выходе из системы блокировка открытых пользователем карточек сохраняется, что позволяет ему вновь войти в систему и продолжить начатую работу.

* *xref:../topics/Management_Cards_View_Locked_Items.adoc[Просмотр списка заблокированных элементов]* +
* *xref:../topics/Management_Cards_Forced_Unlocking.adoc[Принудительное разблокирование элемента]* +
* *xref:../topics/Management_Cards_Updating_List_of_Locks.adoc[Обновление списка блокировок]* +
* *xref:../topics/Management_Cards_File_Locking.adoc[Блокирование и разблокирование файлов документа]* +
