[[ariaid-title1]]
== Управление сессиями

Согласно правилам лицензирования, количество пользователей, одновременно работающих с [.dfn .term]_Docsvision_, ограничивается количеством имеющихся лицензий. При входе пользователя в систему [.dfn .term]_Docsvision_ происходит открытие сессии. Один пользователь одновременно может открыть несколько активных сессий — для этого ему нужно запустить соответствующее количество окон приложения Windows-клиент. При этом все сессии и [.dfn .term]_Личный помощник_, открытые на одном компьютере под одной учетной записью, считаются одним лицензированным соединением. Сессии, открытые под одной учетной записью на разных компьютерах, или открытые на одном компьютере, но под разными учетными записями (разными пользователями), считаются разными соединениями. 

Сессии, открытые службой управления процессами, не считаются лицензированным соединением. Во время работы сервис службы управления процессами открывает не менее четырех сессий (общее число открытых сервисом службы управления процессами сессий зависит от выполняемых им действий и может значительно превышать указанное число). Меньшее количество открытых сессий показывает, что сервис работает некорректно и следует обратиться в службу техподдержки.

При переходе компьютера в спящий режим, а также при сворачивании пользователем окна Windows-клиента в область уведомлений, после определенного периода времени (5 минут) сессия с Docsvision переводится в офлайн режим. В этом режиме сессия не участвует в учете лицензий.

После открытия окна приложения Windows-клиент сессия переходит обратно в онлайн режим. 

[NOTE]
====
[.note__title]#Прим.:# Сессия не переводится в офлайн режим, когда открыта хотя бы одна карточка.
====

Другие клиенты Docsvision обладают собственной логикой перевода сессии в офлайн (к примеру, Web-клиент) или не реализуют подобной функциональности.

* *xref:../topics/Management_Session_View_List_of_Sessions.adoc[Просмотр списка открытых сессий]* +
* *xref:../topics/Management_Session_Close_of_Session_User.adoc[Закрытие сессии пользователя]* +
* *xref:../topics/Management_Session_Updating_List_of_Sessions.adoc[Обновление списка сессий]* +

*На уровень выше:* xref:../topics/Operations_rma.adoc[Описание операций в РМА]
