= Управление сессиями

Согласно правилам лицензирования, количество пользователей, одновременно работающих с {dv}, ограничивается количеством имеющихся лицензий. При входе пользователя в систему {dv} происходит открытие сессии. Один пользователь одновременно может открыть несколько активных сессий -- для этого ему нужно запустить соответствующее количество окон {wincl}а. При этом все сессии и _Личный помощник_, открытые на одном компьютере под одной учетной записью, считаются одним лицензированным соединением. Сессии, открытые под одной учетной записью на разных компьютерах, или открытые на одном компьютере, но под разными учетными записями (разными пользователями), считаются разными соединениями.

Сессии, открытые службой управления процессами, не считаются лицензированным соединением. Во время работы сервис службы управления процессами открывает не менее четырех сессий (общее число открытых сервисом службы управления процессами сессий зависит от выполняемых им действий и может значительно превышать указанное число). Меньшее количество открытых сессий показывает, что сервис работает некорректно и следует обратиться в службу техподдержки.

При переходе компьютера в спящий режим, а также при сворачивании пользователем окна {wincl}а в область уведомлений, после определённого периода времени (5 минут) сессия с {dv} переводится в офлайн режим. В этом режиме сессия не участвует в учете лицензий.

После открытия окна {wincl}а сессия переходит обратно в онлайн режим.

[NOTE]
====
Сессия не переводится в офлайн режим, когда открыта хотя бы одна карточка.
====

Другие клиенты {dv} обладают собственной логикой перевода сессии в офлайн (к примеру, {wc}) или не реализуют подобной функциональности.

