[[ariaid-title1]]
== Язык

Язык интерфейса Windows-клиента определяется настройками. По умолчанию настроен вариант _Использовать язык интерфейса Microsoft Windows_ (язык пользовательского интерфейса Windows-клиента соответствует языку пользовательского интерфейса ОС Windows).

Чтобы выбрать язык явным образом, выполните следующие действия:

. [.ph .cmd]#Откройте окно параметров Windows-клиент, затем выберите набор параметров [.keyword]*Основные*. #
. [.ph .cmd]#В выпадающем списке *Язык интерфейса* выберите нужный вариант языка: #
* Использовать язык интерфейса Microsoft Windows - язык Windows-клиента будет соответствовать текущей локали операционной системы;
* Использовать настройки сервера Docsvision (язык будет определен настройками сервера);
* Английский (ENU);
* Русский (RUS).
+
Дополнительно к приведенным выше вариантам, в списке могут присутствовать языки из используемой лицензии [.dfn .term]_Docsvision_.
. [.ph .cmd]#Нажмите на кнопку *ОК*.#
. [.ph .cmd]#Чтобы изменения вступили в силу, перезапустите приложение [.dfn .term]_Windows-клиент_.#

Открыть Windows-клиент с определенным языком локализации можно запустив программу с параметром `LangName` (см. пункт xref:Application_run_adv.html#concept_ozb_qk2_5db__section_lkx_kr2_5db[Запуск Windows-клиента с дополнительными параметрами из веб-браузера]).

[NOTE]
====
[.note__title]#Прим.:# Windows-клиент поддерживает локализацию следующих элементов пользовательского интерфейса: названия папок, название представлений, колонок представлений и групп представлений, названия поисковых запросов и групп запросов, элементы разметки карточек. Локализованные названия для папок могут быть xref:FolderLocalization.adoc[установлены] пользователями Docsvision – локализация других элементов выполняется при настройке системы Docsvision.
====

*На уровень выше:* xref:../topics/Navigator_settings_main.adoc[Настройка основных параметров Windows-клиента]
