= Язык

Язык интерфейса {wincl}а определяется настройками. По умолчанию настроен вариант _Использовать язык интерфейса Microsoft Windows_ (язык пользовательского интерфейса {wincl}а соответствует языку пользовательского интерфейса ОС Windows).

Чтобы выбрать язык явным образом, выполните следующие действия:

. [.ph .cmd]#Откройте окно параметров {wincl}, затем выберите набор параметров [.keyword]*Основные*. #
. [.ph .cmd]#В выпадающем списке *Язык интерфейса* выберите нужный вариант языка: #
* Использовать язык интерфейса Microsoft Windows -- язык {wincl}а будет соответствовать текущей локали операционной системы;
* Использовать настройки сервера {dv} (язык будет определен настройками сервера);
* Английский (ENU);
* Русский (RUS).
+
Дополнительно к приведенным выше вариантам, в списке могут присутствовать языки из используемой лицензии _{dv}_.
. [.ph .cmd]#Нажмите на кнопку *ОК*.#
. [.ph .cmd]#Чтобы изменения вступили в силу, перезапустите приложение _{wincl}_.#

Открыть {wincl} с определенным языком локализации можно запустив программу с параметром `LangName` (см. пункт xref:Application_run_adv.html#concept_ozb_qk2_5db__section_lkx_kr2_5db[Запуск {wincl}а с дополнительными параметрами из веб-браузера]).

[NOTE]
====
{wincl} поддерживает локализацию следующих элементов пользовательского интерфейса: названия папок, название представлений, колонок представлений и групп представлений, названия поисковых запросов и групп запросов, элементы разметки карточек. Локализованные названия для папок могут быть xref:FolderLocalization.adoc[установлены] пользователями {dv} -- локализация других элементов выполняется при настройке системы {dv}.
====
