[[ariaid-title1]]
== Региональные настройки пользователя для отображения дат и чисел

По умолчанию при использовании определенного xref:Navigator_settings_language.adoc[языка интерфейса Windows-клиента] при отображении дат и чисел используется формат, соответствующий используемому языку интерфейса. Пользователь может изменить данное поведение, чтобы при отображении дат и чисел в Windows-клиенте использовались региональные настройки пользователя из настроек операционной системе.

Чтобы включить использование региональных настроек для отображения дат и чисел:

. [.ph .cmd]#Откройте окно xref:Navigator_settings.html[[.keyword]*Параметры Windows-клиент*], затем выберите набор параметров xref:Navigator_settings_main.html[[.keyword]*Основные*].#
. [.ph .cmd]#Установите флаг [.ph .uicontrol]*Использовать региональные настройки пользователя для отображения дат и чисел*.#
. [.ph .cmd]#Нажмите на кнопку [.ph .uicontrol]*ОК*.#
+
Настройка будет применена после перезапуска Windows-клиента.

*Parent topic:* xref:../topics/Navigator_settings_main.adoc[Настройка основных параметров Windows-клиента]
