[[ariaid-title1]]
== Количество строк в дополнительной области представления

Администратор Docsvision может указать в РМА колонку представления, которая будет отображаться в дополнительной области строки таблицы представления. Данная функция позволяет вывести на экран многострочный текст, используя всю ширину таблицы представления.

Если описанная выше настройка выполнена, в Windows-клиенте можно дополнительно задать количество строк, отображаемых в дополнительной области. По умолчанию настроено отображение трех строк.

Чтобы настроить отображение строк в дополнительной области представления, выполните следующие действия:

[[task_y3d_4qx_vn__steps_zwh_1qx_vn]]
. [.ph .cmd]#Откройте окно параметров Windows-клиент, затем выберите набор параметров [.keyword]*Основные*. #
. [.ph .cmd]#Чтобы настроить отображение определенного количества строк, установите флаг [.ph .uicontrol]*Количество строк в дополнительной области представления*. #
. [.ph .cmd]#Чтобы настроить отображение всех строк, установите флаг [.ph .uicontrol]*Отобразить все строки в дополнительной области представления*.#
. [.ph .cmd]#Нажмите на кнопку *ОК*. #

*На уровень выше:* xref:../topics/Navigator_settings_main.adoc[Настройка основных параметров Windows-клиента]
