[[ariaid-title1]]
== Возможности поиска

[.dfn .term]_Рабочее место Администратора Docsvision_ (далее – [.dfn .term]_РМА_) предоставляет несколько видов поиска:

* [.keyword]*Поиск папки* осуществляет контекстный поиск папки по ключевой строке, которая может представлять собой сочетание символов, слово или фразу. В результате такого поиска будет выделена первая найденная папка, отвечающая заданному условию.
* [.keyword]*Поиск по представлению* – это контекстный поиск карточек в текущем представлении по ключевой строке, которая может представлять собой сочетание символов, слово или фразу. В результате такого поиска будет выделена первая карточка, отвечающая заданному условию. См. xref:Views_Search_View.adoc[Поиск карточки по представлению];
* [.keyword]*Расширенный поиск* выполняется на основе поисковых запросов (см. следующий раздел), которые позволяют производить поиск карточек в соответствии с определенными критериями. Результаты последнего поиска отображаются в виртуальной папке [.keyword]*Результаты поиска*, которая автоматически создается при первом запуске [.dfn .term]_РМА_;
* поиск карточек при помощи *Личного помощника*. Поиск осуществляется на основе запросов, аналогичных запросам для расширенного поиска, однако выполняется системой самостоятельно через определенные интервалы времени и может производиться как при открытом, так и при закрытом основном пользовательском приложении – [.dfn .term]_РМА_.
+
[NOTE]
====
[.note__title]#Прим.:# В результаты поиска попадут только те карточки, к которым пользователю разрешен доступ.
====
* [.keyword]*Быстрый поиск* значений в полях и таблицах открытых карточек. Поиск выполняется аналогично в Windows-клиенте и РМА. См. xref:Search_substring.adoc[Быстрый поиск по подстроке].

* *xref:../topics/Search_Folder_Search.adoc[Поиск папки]* +
* *xref:../topics/Search_Search_View.adoc[Поиск карточки по представлению]* +
* *xref:../topics/Search_Advanced_Search.adoc[Расширенный поиск]* +

*На уровень выше:* xref:../topics/Operations_rma.adoc[Описание операций в РМА]
