[[ariaid-title1]]
== Атрибутивный поиск карточки

Атрибутивный поиск представляет собой поиск карточек по значениям их полей. Атрибутивный поиск обладает следующими возможностями:

* Поиск может выполняться по одному или нескольким полям заданных типов карточек. Условия атрибутивного поиска определяются в соответствии со следующей схемой: [.keyword .parmname]_<Название поля><Логический оператор><Атрибут: Значение поля/Параметр/Поисковое слово>_.
* Условия атрибутивного поиска могут объединяться с условиями полнотекстового поиска логическим оператором «ИЛИ» (если достаточно выполнения только одного из условий) или «И» (если необходимо, чтобы выполнялись все условия поиска).
* Условия атрибутивного поиска среди карточек одного типа могут объединяться логическим оператором «ИЛИ» (если достаточно выполнения только одного из условий) или «И» (если необходимо, чтобы выполнялись все условия поиска).
* Поиск может выполняться в определенных папках, указанных на вкладке [.keyword]*Папки* диалогового окна [.keyword .wintitle]*Расширенный поиск*.
* Поиск может выполняться среди карточек, типы которых указаны на вкладке [.keyword]*Типы* диалогового окна [.keyword .wintitle]*Расширенный поиск*.

Условия атрибутивного поиска определяются на вкладке [.keyword]*Атрибутивный* диалогового окна [.keyword .wintitle]*Расширенный поиск*.

*На уровень выше:* xref:../topics/Search_Advanced_Search.adoc[Расширенный поиск]
