= Возможности поиска

_Рабочее место Администратора {dv}_ (далее -- _РМА_) предоставляет несколько видов поиска:

* *Поиск папки* осуществляет контекстный поиск папки по ключевой строке, которая может представлять собой сочетание символов, слово или фразу. В результате такого поиска будет выделена первая найденная папка, отвечающая заданному условию.
* *Поиск по представлению* -- это контекстный поиск карточек в текущем представлении по ключевой строке, которая может представлять собой сочетание символов, слово или фразу. В результате такого поиска будет выделена первая карточка, отвечающая заданному условию. См. xref:Views_Search_View.adoc[Поиск карточки по представлению];
* *Расширенный поиск* выполняется на основе поисковых запросов (см. следующий раздел), которые позволяют производить поиск карточек в соответствии с определенными критериями. Результаты последнего поиска отображаются в виртуальной папке *Результаты поиска*, которая автоматически создается при первом запуске _РМА_;
* поиск карточек при помощи *Личного помощника*. Поиск осуществляется на основе запросов, аналогичных запросам для расширенного поиска, однако выполняется системой самостоятельно через определенные интервалы времени и может производиться как при открытом, так и при закрытом основном пользовательском приложении -- _РМА_.
+
[NOTE]
====
В результаты поиска попадут только те карточки, к которым пользователю разрешен доступ.
====
* *Быстрый поиск* значений в полях и таблицах открытых карточек. Поиск выполняется аналогично в {wincl}е и РМА. См. xref:Search_substring.adoc[Быстрый поиск по подстроке].

* *xref:../topics/Search_Folder_Search.adoc[Поиск папки]* +
* *xref:../topics/Search_Search_View.adoc[Поиск карточки по представлению]* +
* *xref:../topics/Search_Advanced_Search.adoc[Расширенный поиск]* +
