= Работа с представлениями

_Представлением_ называется таблица, в которой отображается информация о карточках в _Области представления_. Главным достоинством табличного представления данных является то, что оно позволяет отобразить информацию о карточках различных типов в одной таблице, позволяя выводить на экран только необходимые поля и обеспечивая регулирование высоты строк и ширины столбцов в зависимости от текущих потребностей пользователя.

Для любой папки можно выбрать представление, наиболее наглядно отражающее информацию содержащихся в ней карточек и не включающее избыточной информации.

Поскольку просмотр может осуществляться в целях получения различной информации, можно выбрать для папки несколько представлений, каждое из которых будет отвечать какой-либо одной из поставленных задач (для этого следует создать папку-делегат и определить для нее другое представление).

По умолчанию информация вновь создаваемой папки отображается в виде стандартного представления -- дайджеста, кратко описывающего карточку одной строкой текста. Для каждого типа карточки предусмотрен определенный дайджест.

Представление, как и любая таблица, состоит из колонок и строк. Строки таблицы могут представлять собой карточки, ярлыки карточек, строки секций карточек (например, в представлении по справочникам) и т. п. Колонки таблицы выбираются пользователем в зависимости от назначения представления в окне [.keyword .wintitle]*Настройка данных представления* (например, [.keyword .parmname]_Автор_, [.keyword .parmname]_Дата создания_, [.keyword .parmname]_Название_).

* *xref:../topics/Views_Digest_and_Custom_Views.adoc[Дайджест и пользовательские представления]* +
* *xref:../topics/Views_Tools_Views_on_Organization_of_Data.adoc[Использование представлений]* +
