= Работа с представлениями

Работа с представлениями предполагает работу с большим объемом данных. Чтобы облегчить пользователю просмотр таблицы, содержащей большое количество строк, а также обеспечить возможность экспорта в другие форматы и печати, приложении предусмотрены ряд настроек:

* xref:ViewArea_colour_label.adoc[Использование цветовых меток];
* xref:ViewArea_tab_control.adoc[Управление столбцами представления];
* xref:ViewArea_sorting.adoc[Сортировка данных представления];
* xref:ViewArea_grouping.adoc[Группировка данных представления];
* xref:ViewArea_filtering.adoc[Фильтрация данных представления];
* xref:ViewArea_change_view_type.adoc[Смена вида представления];
* xref:ViewArea_search.adoc[Поиск по представлению];
* xref:ViewArea_print.adoc[Печать данных представления];
* xref:ViewArea_export.adoc[Экспорт данных представления].

[[concept_tdz_cj4_gn__section_cmj_4fq_y3b]]
== Особенности работы с представлениями

* Если изменение настроек представлений папки выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_.
* При возникновении проблем с отображением данных в представлении, попробуйте обновить представление с зажатой клавишей SHIFT.
