= Печать содержимого папки в текущем представлении

Для печати содержимого папки в текущем представлении выполните следующие действия:

. Вызовите окно настроек печати одним из способов:
* нажмите кнопку *Печать* на панели инструментов _РМА_;
* выберите из главного меню _РМА_ menu:Файл[Печать];
* нажмите на клавиатуре сочетание клавиш kbd:[Ctrl + P].
+
Будет открыто стандартное диалоговое окно *Настройки печати* (*Print Setup*).
+
. При необходимости измените настройки печати, сделав их отличными от доступных по умолчанию:
* _Размер_ бумаги;
* _Источник_ бумаги (набор доступных для выбора в этом поле возможностей зависит от марки принтера);
* _Ориентацию_ бумаги (`Портретная`, `Альбомная`);
* _Свойства_ принтера, полный набор которых также зависит от марки принтера;
* Выберите один из имеющихся в сети и доступных пользователю принтеров, не установленных для него по умолчанию, нажав кнопку *Сетевой...*.
. Нажмите кнопку *Печать*.
+
На принтер будут выведены сведения обо всех элементах папки, выбранной в левой панели _РМА_, в текущем представлении.
