[[ariaid-title1]]
== Использование представлений

В зависимости от назначения представления, пользователь может изменять порядок, в котором отображаются строки и колонки таблицы, представленной в области просмотра содержимого папки, а именно:

* сортировать карточки в определенном порядке (например, в алфавитном порядке по названию карточки);
* группировать карточки по общему признаку;
* автоматически фильтровать карточки по данным какой-либо колонки, оставляя на экране только нужные;
* изменять размеры строк и порядок следования колонок таблицы.

Каждый пользователь может установить для любой доступной ему папки удобное для него представление (см. раздел xref:Folders_Change_of_View.adoc[Смена представления]).

Настройки сортировки и группировки данных представления, изменения порядка и ширины столбцов сохраняются в системе и не требуют повторной настройки (но только до момента изменения авторских настроек представления); в этом случае они будут применены при следующем открытии [.dfn .term]_РМА_.

Подробнее о сохранении пользовательских настроек см. xref:Folders_SavingCancellation_User_Settings.adoc[Сохранение и отмена пользовательских настроек].

* *xref:../topics/Folders_Sorting_Data.adoc[Сортировка данных]* +
* *xref:../topics/Views_Grouping_Data_Representation.adoc[Группировка данных представления]* +
* *xref:../topics/Views_Data_Filtering.adoc[Автоматическая фильтрация данных представления]* +
* *xref:../topics/Views_Resizing_Rows.adoc[Изменение размеров строк]* +
* *xref:../topics/Views_Reordering_Columns.adoc[Изменение порядка колонок]* +
* *xref:../topics/Views_Highlighting_Color.adoc[Выделение строк представления цветом]* +
* *xref:../topics/Views_Search_View.adoc[Поиск карточки по представлению]* +
* *xref:../topics/Views_Output_of_Print_View_Arm.adoc[Печать содержимого папки в текущем представлении]* +

*На уровень выше:* xref:../topics/Views_Working_with_Views.adoc[Работа с представлениями]
