= Использование представлений

В зависимости от назначения представления, пользователь может изменять порядок, в котором отображаются строки и колонки таблицы, представленной в области просмотра содержимого папки, а именно:

* сортировать карточки в определённом порядке (например, в алфавитном порядке по названию карточки);
* группировать карточки по общему признаку;
* автоматически фильтровать карточки по данным какой-либо колонки, оставляя на экране только нужные;
* изменять размеры строк и порядок следования колонок таблицы.

Каждый пользователь может установить для любой доступной ему папки удобное для него представление (см. раздел xref:rma/Folders_Change_of_View.adoc[Смена представления]).

Настройки сортировки и группировки данных представления, изменения порядка и ширины столбцов сохраняются в системе и не требуют повторной настройки (но только до момента изменения авторских настроек представления); в этом случае они будут применены при следующем открытии _РМА_.

Подробнее о сохранении пользовательских настроек см. xref:rma/Folders_SavingCancellation_User_Settings.adoc[Сохранение и отмена пользовательских настроек].
