[[ariaid-title1]]
== Печать содержимого папки в текущем представлении

Для печати содержимого папки в текущем представлении выполните следующие действия:

. [.ph .cmd]#Вызовите окно настроек печати одним из способов:#
* нажмите кнопку [.ph .uicontrol]*Печать* на панели инструментов [.dfn .term]_РМА_;
* выберите из главного меню [.dfn .term]_РМА_ [.ph .menucascade]#[.ph .uicontrol]*Файл* > [.ph .uicontrol]*Печать*#;
* нажмите на клавиатуре сочетание клавиш [.ph .uicontrol]*Ctrl + P*.
+
Будет открыто стандартное диалоговое окно [.ph .uicontrol]*Настройки печати* ([.ph .uicontrol]*Print Setup*).
. [.ph .cmd]#При необходимости измените настройки печати, сделав их отличными от доступных по умолчанию: #
* [.keyword .parmname]_Размер_ бумаги;
* [.keyword .parmname]_Источник_ бумаги (набор доступных для выбора в этом поле возможностей зависит от марки принтера);
* [.keyword .parmname]_Ориентацию_ бумаги ([.kbd .ph .userinput]`Портретная`, [.kbd .ph .userinput]`Альбомная`);
* [.keyword .parmname]_Свойства_ принтера, полный набор которых также зависит от марки принтера;
* выберите один из имеющихся в сети и доступных пользователю принтеров, не установленных для него по умолчанию, нажав кнопку [.ph .uicontrol]*Сетевой...*.
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Печать*.#
+
На принтер будут выведены сведения обо всех элементах папки, выбранной в левой панели [.dfn .term]_РМА_, в текущем представлении.

*На уровень выше:* xref:../topics/Views_Tools_Views_on_Organization_of_Data.adoc[Использование представлений]
