= Сортировка данных представления

[IMPORTANT]
====
В {wincl}е не работает (работает некорректно) сортировка по столбцу с вычисляемым полем, в котором используется функция конкатенации.

Из-за существующего ограничения MicrosoftSQL возможно "обрезание" части данных в строках столбцов, по которым выполнена сортировка, если суммарное количество данных в этих столбах превысит существующее ограничение -- около 4000 символов для текстовых данных (для других типов данных значение может отличаться).
====

Сортировка карточек, представленных в виде таблицы, позволяет упорядочить их по одному из столбцов в прямом или обратном порядке.

Каждая последующая сортировка данных отменяет результаты предыдущей. Однако, если проводить сортировку при нажатой клавише kbd:[Shift], предыдущие настройки сброшены не будут, и данные будут отсортированы по нескольким столбцам (максимально -- по 4 столбцам).

При этом новые настройки будут применены "внутри" старых. Например, если провести сортировку по столбцу _Тип карточки_, а затем (при нажатой клавише kbd:[Shift]) по столбцу _Создана_, карточки будут отсортированы по типу, а внутри каждого типа -- также по дате создания.

Сортировка всегда производится по всему массиву данных, даже если они выводятся постранично. После выполнения сортировки будет выбрана первая строка первой страницы представления.

В колонках с типом данных _Целое число_ или _Дробное число_ большие числа будут выводиться с разделением на триады (например: `1 000 000`, `2 345 400.56`). Сортировка при этом будет работать в соответствии с типом данных, указанных для столбца.

. Чтобы отсортировать строки по какому-либо столбцу, щелкните по заголовку этого столбца.
+
В заголовке столбца появится значок сортировки.
+
. Чтобы сменить направление сортировки, повторно щелкните по заголовку того же столбца.
