= Работа с представлениями

Работа с представлениями предполагает работу с большим объемом данных. Чтобы облегчить пользователю просмотр таблицы, содержащей большое количество строк, а также обеспечить возможность экспорта в другие форматы и печати, в приложении предусмотрен ряд настроек:

* xref:views-color-labels.adoc[Использование цветовых меток].
* xref:views-configure.adoc[Управление столбцами представления].
* xref:views-sort.adoc[Сортировка данных представления].
* xref:views-group.adoc[Группировка данных представления].
* xref:views-filter.adoc[Фильтрация данных представления].
* xref:views-change-view.adoc[Смена вида представления].
* xref:views-search.adoc[Поиск по представлению].
* xref:views-print.adoc[Печать данных представления].
* xref:views-export.adoc[Экспорт данных представления].

== Особенности работы с представлениями

* Если изменение настроек представлений папки выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска _{wincl}а_.
* При возникновении проблем с отображением данных в представлении, попробуйте обновить представление с зажатой клавишей kbd:[Shift].
