= Настройка области представления

При работе с областью представления имеется ряд особенностей.

== Отображение большого количества карточек

В случае, если представление содержит слишком много карточек (по умолчанию более `5000`) и в его настройках не указано максимальное число карточек на одной странице, появится диалог с предложением использовать постраничный вывод. Чтобы данный диалог не отображался, следует заранее указать максимальное количество карточек на одной странице в настройках представления для папки.

== Использование сохранённых представлений

Если к папке было применено сохранённое представление, и после этого пользователь изменил в нём какие-либо параметры (например, группировку или сортировку), данное сохранённое представление будет применяться к другой папке уже с этими изменениями.

NOTE: Данное правило действует в рамках текущей сессии.

Чтобы вернуть настройки по умолчанию, то есть применить изначальное сохранённое представление без каких-либо правок, нажмите на ленте {wincl}а кнопку *Обновить*, удерживая клавишу kbd:[Shift].

Пользовательские настройки представления сохраняются в рамках текущей сессии.

== Отображение колонки "Метка"

См. xref:views-color-labels.adoc[Использование цветовых меток]
