= Сортировка данных представления

[NOTE]
====
[.note__title]#Важное замечание:# В {wincl}е не работает (работает некорректно) сортировка по столбцу с вычисляемым полем, в котором используется функция конкатенации.

Из-за существующего ограничения MicrosoftSQL возможно "обрезание" части данных в строках столбцов, по которым выполнена сортировка, если суммарное количество данных в этих столбах превысит существующее ограничение -- около 4000 символов для текстовых данных (для других типов данных значение может отличаться).
====

Сортировка карточек, представленных в виде таблицы, позволяет упорядочить их по одному из столбцов в прямом или обратном порядке.

Каждая последующая сортировка данных отменяет результаты предыдущей. Однако, если проводить сортировку при нажатой клавише [.kbd .ph .userinput]`Shift`, предыдущие настройки сброшены не будут, и данные будут отсортированы по нескольким столбцам (максимально -- по 4 столбцам). При этом новые настройки будут применены как бы "внутри" старых. Например, если провести сортировку по столбцу [.keyword]*Тип карточки*, а затем (при нажатой клавише [.kbd .ph .userinput]`Shift`) по столбцу [.keyword]*Создана*, карточки будут отсортированы по типу, а внутри каждого типа -- еще и по дате создания.

Сортировка всегда производится по всему массиву данных, даже если они выводятся постранично. После выполнении сортировки будет выбрана первая стройка первой страницы представления.

[#task_q1g_mr4_gn__view_sorting .ph]#Для колонок с типом данных _Целое число_ или _Дробное число_ для больших чисел данные колонки будут выводиться с разделением на триады (например: 1000000, 2345400.56). Сортировка при этом будет работать в соответствии с типом данных, указанных для столбца.#

. [.ph .cmd]#Для сортировки строк по какому-либо столбцу, щелкните по заголовку этого столбца.#
+
В заголовке столбца появится значок сортировки.
. [.ph .cmd]#Для смены направления сортировки повторно щелкните по заголовку того же столбца. #
