= Настройка "Области представления"

При работе с Областью представления имеется ряд особенностей.

== Отображение большого количества карточек

В случае, если представление содержит слишком много карточек (по умолчанию более 5000) и в его настройках не указано максимальное число карточек на одной странице, то будет предложено использовать постраничный вывод. Для того чтобы избежать показа данного диалога, следует заранее настроить представление для папки.

== Использование сохраненных представлений

Если к папке применено сохраненное представление, и после этого пользователь изменил в нём какие-либо параметры (например, группировку или сортировку), то к другой папке сохраненное представление будет применяться уже с этими изменениями (в рамках текущей сессии).

Чтобы вернуть настройки по умолчанию, то есть применить изначальное сохраненное представление без каких-либо правок, следует нажать на ленте {wincl}а кнопку *Обновить*, удерживая клавишу kbd:[Shift].

Пользовательские настройки представления сохраняются в рамках текущей сессии.

== Отображение колонки "Метка"

См. xref:ViewArea_colour_label.adoc[Использование цветовых меток]
