= Дайджест и пользовательские представления

Пользователь может оставить представление данных, установленное по умолчанию, выбрать его из уже существующих или определить самостоятельно.

По умолчанию устанавливается универсальное представление карточек -- дайджест, который может использоваться для карточек любого типа. Дайджест состоит из четырех колонок: _Тип карточки_ (входящий документ, исходящий документ, процесс и т. д.), _Дайджест карточки_ (для документа -- название документа и его номер, для файла -- файл и название, для процесса -- название), _Создана_ (дата создания карточки) и _Изменена_ (дата последнего изменения).

Представления, создаваемые пользователем, должны определяться в соответствии с их назначением и включать все необходимые сведения, содержащиеся в карточках (например, для построения отчетов).

[NOTE]
====
Сотрудник сможет работать с пользовательскими представлениями только в том случае, если ему выданы права на чтение данных из карточки сохраненных поисковых запросов.
====
