[[ariaid-title1]]
== Управление рабочими группами

В рамках системы [.dfn .term]_Docsvision_ для объединения сотрудников используются группы, создание которых выполняется в [.dfn .term]_Справочнике сотрудников_. Однако, доступ к данному справочнику у некоторых пользователей может быть ограничен настройками дискреционной безопасности. В этом случае, использование механизма управления рабочими группами остается единственным возможным средством объединения сотрудников. Группы, создаваемые данным способом, будут созданы как группы [.dfn .term]_Справочника сотрудников_, и могут настраиваться как средствами управления рабочими группами, так и средствами справочника.

[NOTE]
====
[.note__title]#Внимание:# Возможности настройки групп в [.dfn .term]_Справочнике сотрудников_ преобладают над настройками групп при помощи механизма управления рабочими группами.
====

Возможность управления рабочими группами доступна только при наличии у пользователя установленного приложения [.dfn .term]_Управление документами_. При выполнении данного условия в [.dfn .term]_Справочнике сотрудников_ добавляется служебная группа [.keyword]*Администраторы РГ*. При включении пользователя в данную группу у пользователя на ленте приложения [.dfn .term]_Windows-клиент_ появляется дополнительная вкладка [.keyword]*Рабочие группы*, включающая команды для добавления новой группы, добавления участников в существующую группу, а также редактирования и удаления групп.

Описание возможностей по управлению рабочими группами содержатся в документе [.ph]#[.dfn .term]_Приложение «Docsvision 5. Управление документами». Руководство пользователя_#.

*На уровень выше:* xref:../topics/Operations_winclient.adoc[Описание операций в Windows-клиенте]
