= Управление рабочими группами

В рамках системы {dv} для объединения сотрудников используются группы, которые создаются в _Справочнике сотрудников_. Однако, доступ к данному справочнику у некоторых пользователей может быть ограничен настройками дискреционной безопасности. В таком случае использование механизма управления рабочими группами остается единственным возможным средством объединения сотрудников.

Группы, создаваемые данным способом, будут созданы как группы _Справочника сотрудников_, и могут настраиваться как средствами управления рабочими группами, так и средствами справочника.

[CAUTION]
====
Группы, настроенные в _Справочнике сотрудников_, преобладают над настройками групп с помощью механизма управления рабочими группами.
====

Управление рабочими группами доступно, только если у пользователя установлено приложение _{dm}_. Если данное приложение установлено, в _Справочнике сотрудников_ добавляется служебная группа _Администраторы РГ_.

Когда пользователь включён в данную группу, у него на ленте {wincl}а появляется дополнительная вкладка _Рабочие группы_, включающая команды для создания новой группы, добавления участников в существующую группу, а также редактирования и удаления групп.

Описание возможностей по управлению рабочими группами содержатся в руководстве пользователя _Приложения "{dv} 5. {dm}"_.
