= Управление рабочими группами

В рамках системы _{dv}_ для объединения сотрудников используются группы, создание которых выполняется в _Справочнике сотрудников_. Однако, доступ к данному справочнику у некоторых пользователей может быть ограничен настройками дискреционной безопасности. В этом случае, использование механизма управления рабочими группами остается единственным возможным средством объединения сотрудников. Группы, создаваемые данным способом, будут созданы как группы _Справочника сотрудников_, и могут настраиваться как средствами управления рабочими группами, так и средствами справочника.

[CAUTION]
====
Возможности настройки групп в _Справочнике сотрудников_ преобладают над настройками групп при помощи механизма управления рабочими группами.
====

Возможность управления рабочими группами доступна только при наличии у пользователя установленного приложения _{dm}_. При выполнении данного условия в _Справочнике сотрудников_ добавляется служебная группа *Администраторы РГ*. При включении пользователя в данную группу у пользователя на ленте {wincl}а появляется дополнительная вкладка *Рабочие группы*, включающая команды для добавления новой группы, добавления участников в существующую группу, а также редактирования и удаления групп.

Описание возможностей по управлению рабочими группами содержатся в документе _Приложение "{dv} 5. {dm}". Руководство пользователя_.
