= Управление рабочими группами

В рамках системы _{dv}_ для объединения сотрудников используются группы, создание которых выполняется в _Справочнике сотрудников_. Однако, доступ к данному справочнику у некоторых пользователей может быть ограничен настройками дискреционной безопасности. В этом случае, использование механизма управления рабочими группами остается единственным возможным средством объединения сотрудников. Группы, создаваемые данным способом, будут созданы как группы _Справочника сотрудников_, и могут настраиваться как средствами управления рабочими группами, так и средствами справочника.

[NOTE]
====
[.note__title]#Внимание:# Возможности настройки групп в _Справочнике сотрудников_ преобладают над настройками групп при помощи механизма управления рабочими группами.
====

Возможность управления рабочими группами доступна только при наличии у пользователя установленного приложения _Управление документами_. При выполнении данного условия в _Справочнике сотрудников_ добавляется служебная группа [.keyword]*Администраторы РГ*. При включении пользователя в данную группу у пользователя на ленте приложения _{wincl}_ появляется дополнительная вкладка [.keyword]*Рабочие группы*, включающая команды для добавления новой группы, добавления участников в существующую группу, а также редактирования и удаления групп.

Описание возможностей по управлению рабочими группами содержатся в документе [.ph]#_Приложение "{dv} 5. Управление документами". Руководство пользователя_#.
