= Исправленные ошибки

* DV5-1036. Область полнотекстового поиска "Искать в найденном" не сбрасывалась при нажатии на кнопку отмены (красный крестик).
* DV5-1118. В представлении при группировке по вещественному полю в группе выводились лишние знаки, несмотря на применяемый формат.
* DV5-1303. Исправлена ошибка, не позволявшая изменить иконку для папки "Результаты поиска".
* DV5-1449. При обновлении папки, введенные в поле полнотекстового поиска данные для поисковой папки не сохранялись.
* DV5-2539 (SUP-694). Возникала ошибка "Не удалось получить данные представления" при попытке открыть представление в постраничном режиме.
* DV5-2596 (SUP-869). Исправлена ошибка, из-за которой некорректно работала сортировка столбцов: при сортировке в поисковой папке вместо видов документа отображались записи вида "Docsvision.Platform.Cards….".
* DV5-2610 (SUP-905). Исправлена ошибка, вызывавшая самопроизвольное закрытие Windows-клиента при переходе из виртуальной папки, для которой настроен поисковой фильтр.
* DV5-2615 (SUP-929). Исправлена ошибка, из-за которой поле смены представления по умолчанию в свойствах папки у виртуальных папок оказывалось заблокировано.
* DV5-2642 (SUP-978). Не удавалось открыть карточка по ссылке из Chrome с помощью Docsvision Windows Client Launcher.
* DV5-2644 (SUP-985). При отображении карточек в представлении возникала ошибка. У пользователя с правами только на чтение в представлении отображались не все карточки, если ограничение в количестве выводимых записей не равнялось количеству карточек.
* DV5-2651 (SUP-978). Запуск Windows-клиента в Google Chrome через приложение Docsvision Windows Client Launcher не работал в версиях браузера выше 45.0.
* DV5-2696 (SUP-1021). При попытке запустить новый процесс Windows-клиента во время завершения предыдущего, завершались оба процесса.
* DV5-2793 (SUP-1147). Исправлена ошибка, когда невозможно было уменьшить ширину крайней правой колонки в представлении папки.
* DV5-2793 (SUP-2642). Исправлена ошибка, когда невозможно было уменьшить ширину крайней правой колонки в представлении папки.
* DV5-2793 (SUP-2642, SUP-1147). Исправлена ошибка, когда невозможно было уменьшить ширину крайней правой колонки в представлении папки.
* DV5-2817 (SUP-1152). При изменении метаданных разными пользователями сохранялось только последне выполненное изменение.
* DV5-2932 (SUP-1254). Исправлена ошибка, из-за которой отключалась постраничная проверка прав доступа, если в настройках представления было задано дополнительное условие.
* DV5-3188 (SUP-1366). Исправлена ошибка, из-за которой не работал сбор расширенного журнала при сканировании.
* DV5-3659 (SUP-1489). При полнотекстовом поиске не отображались архивированные карточки из сателлитной БД.
* DV5-3660 (SUP-2362, SUP-1916). При открытии в РМА журналов работы Docsvision использовались фильтры по умолчанию, а не фильтры, установленные в системных настройках журналирования.
* DV5-400. Исправлена ошибка, вызывавшая изменение высоты нижней панели при перемещении по главному окну Windows-клиента.
* DV5-4026 (SUP-1865). Возникала ошибка при выполнении CardHost.SelectCard в Справочнике дополнительных команд.
* DV5-4059 (SUP-1888). Исправлена ошибка, при которой запрет на установку библиотеки карточек в консоли настроек вызывал уведомление о несоответствии версий в Windows-клиенте.
* DV5-4114 (SUP-1980). Windows-клиент не запускался из Chrome через плагин Docsvision Windows Client Launcher, если использовалось подключение по https.
* DV5-4453. Во время печати представления формировалось большое количество лишних одинаковых страниц, или становился недоступным Windows-клиент.
* DV5-4720 (SUP-2580). Не выполнялось обновление клиентской части модуля, установленной для всех пользователей, если пакет установки был запущен без флага "allusers".
* DV5-4812 (SUP-2634). Исправлена ошибка, когда не сбрасывались настройки представления при нажатой клавише Shift.
* DV5-4812 (SUP-2634, SUP-2638). Исправлена ошибка, когда не сбрасывались настройки представления при нажатой клавише Shift.
* DV5-4812 (SUP-2638). Исправлена ошибка, когда не сбрасывались настройки представления при нажатой клавише Shift.
* DV5-4853 (SUP-2718). Исправлена ошибка, при которой не работала инвалидация кэшированного дайджеста метаданных в DocsVision.ObjectModel.dll. Ошибка не позволяла работать с расширенным полем, созданным другим пользователем.
* DV5-4879 (SUP-2774). Не работал поиск по представлению с несколькими уровнями вложенности.
* DV5-5052 (SUP-2955). Исправлена ошибка, когда при автоматическом обновлении содержимого папки значения параметров поиска принимались по умолчанию, несмотря на заданные настройки. Из-за ошибки в папке отображались неправильные карточки или не отображались вовсе.
* DV5-5055 (SUP-2911). Исправлена ошибка, когда при добавлении отсканированного документа несколькими запусками сканера, на некоторых сканерах сканирование не удавалось запустить больше одного раза.
* DV5-5057 (SUP-2820). После создания собственного элемента управления, ЭУ не получалось добавить через справочник компонентов из-за того, что Windows-клиент не загружал файл библиотеки resources на машине без DevExpress.
* DV5-5058 (SUP-2685). Возникала массовая ошибка в БП: "System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully".
* DV5-5174 (SUP-3041). Исправлена ошибка, когда крайняя правая колонка представления переставала отображаться полностью в Windows-клиенте, если обновить представление с Shift в окне на весь экран.
* DV5-5175 (SUP-3041). Исправлена ошибка, вызывавшая постепенное сокращение ширины крайней правой колонки представления после обновления представления.
* DV5-5253 (SUP-2994). Исправлена ошибка, из-за которой блокировалось автоматическое удаление ярлыков из папки "Последние", в которой имелся ярлык с незаданной датой.
* DV5-5262 (SUP-3058). При выгрузке в Excel не учитывались теги скрытых колонок.
* DV5-5367 (SUP-3205). Исправлена ошибка, когда после перезапуска сервисов Docsvision папки, настроенные на автоматическое обновление, переставали обновляться.
* DV5-5383 (SUP-3895). Выбор области полнотекстового поиска по умолчанию при открытии папки по умолчанию устанавливался на "Везде", вместо "В текущей папке".
* DV5-5623 (SUP-3328). Возникала ошибка при сканировании документа: "Scanner error message: Out of memory error".
* DV5-5623 (SUP-3651, SUP-3328). Возникала ошибка при сканировании документа: "Scanner error message: Out of memory error".
* DV5-5711. В Справочнике видов карточек можно было удалить вид, подвиды которого заблокированы.
* DV5-5738 (SUP-3699). Возникало сообщение "Делегаты не выбраны" при вызове окна делегирования через Alt+Q и выборе сотрудника из раскрывающегося списка клавишей Enter.DV5-5666.
* DV5-5894 (SUP-3872). Скрытая колонка "Метки" в представлении папки повторно начинала отображаться после повторного открытия Windows-клиента.
* DV5-5931 (SUP-3970). В инсталлятор добавлены русские ресурсы DevExpress.
* DV5-6028 (SUP-4139). Исправлена ошибка, при которой не работал пулинг SQL соединений с сервером Postgres из-за того, что соединения каждый раз создавались заново.
* DV5-6059 (SUP-4185). Поисковые запросы, добавленные через Web-клиент, отображались в Windows-клиенте отдельной категорией.
* DV5-6060 (SUP-4180). При отображении сообщения об ошибке возникало другое сообщение об ошибке, что приводило к зацикливанию ошибок в исключении System.Runtime.InteropServices.COMException.
* DV5-6122 (SUP-4311). При сохранении настроек ограничений прикрепленных файлов появлялось некорректное сообщение об ошибке.
* DV5-6137 (SUP-4313). В Windows-клиенте возникала ошибка "Не удалось отобразить настройки пользователя" в результате которой расширения в коллекции добавлялись как null.
* DV5-6173 (SUP-4378). В Windows-клиенте возникала ошибка "Не удалось выполнить поисковый запрос" при добавлении в поиск параметра Сотрудник - Текущие состояние сотрудника.
* DV5-6299 (SUP-4574, SUP-4766, SUP-4518). Исправлена ошибка, при которой в окне фильтрации формат даты самопроизвольно менялся на на 12-часовой.
* DV5-6313 (SUP-4522). Исправлена ошибка, при которой не происходила отписка от события при смене состояния карточки документа.
* DV5-6404 (SUP-4679). В консоли настройки отсутствовал BackOffice SnapIn для шифрования учётных данных.
* DV5-6408 (SUP-4620). В карточке документа, открытой через задание, прокрутка не прокручивала до конца.
* DV5-6448 (SUP-4738). Исправлена ошибка, когда после обновления модуля Платформа до версии 5.5.3 инициатору согласования становилась недоступна кнопка Завершить этап если он не состоял в группе Администраторы КС.
* DV5-6453 (SUP-4645). Возникала ошибка при попытке создания подразделения в справочнике контрагентов, если для карточки вида подразделения контрагента добавлена секция типа структура и поле RefCardId для хранения ссылок на другие карточки.
* DV5-6525 (SUP-4898). В представлениях представлениях Windows-клиента использовались не локализованные булевы значения в фильтре.
* DV5-6574 (SUP-4977). Возникала ошибка "Attempted to divide by zero" при подсчете с настроенной агрегацией по среднему значению поля.
* SUP-1608. При открытии задания возникала ошибка "Индекс находился вне границ массива".
* SUP-1841. Права на файлы библиотек в справочнике компонентов не применялись для конечных пользователей.
* SUP-1867. В диалоге сканирования возникала ошибка "See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box", если служба WIA была отключена.
* SUP-1994. При запуске Windows-клиента на клиентской машине возникало сообщение: "The version of the card library "System cards (.NET)" (not installed) does not match the version requested by server".
* SUP-2048. Исправлена ошибка, из-за которой после обновления модуля Платформа до версии 5.5 не работало представление Акты сверок.
* SUP-2363. Исправлена ошибка "Collection was modified; enumeration operation may not execute" на функции задания.
* SUP-2642. Исправлена ошибка, когда невозможно было уменьшить ширину крайней правой колонки в представлении папки.
* SUP-2745. При нажатии на кнопку параметров Windows-клиента возникала ошибка "Не удалось отобразить настройки пользователя. Ссылка на объект не указывает на экземпляр объекта".
* SUP-280. В диалоге сканирования возникала ошибка "See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box", если служба WIA была отключена.
* SUP-2966. Во время разработки собственного вида карточки, при попытке активации вида возникала ошибка "Не удалось открыть карточку".
* SUP-3138. Исправлена ошибка, возникавшая при многостраничном сканировании: "Не удалось осуществить сканирование. Acquired method can be executed only if device is set as current device in device manager".
* SUP-3499. Файл модуля Делопроизводство 4.5 во время согласования оставался заблокированным заблокированным согласующим и не загружался в систему.
* SUP-3692. Возникала ошибка при попытке переименования файла в карточке.
* SUP-3859. Исправлена ошибка, из-за которой не отображался полный текст под полем выпадающего списка писем.
* SUP-747. Исправлена ошибка, при которой после обновления Docsvision до версии 5.5, кнопка "Создать документ" оказывалась доступна только администраторам.