//tag::conn-address[]
* `Username` -- имя пользователя для подключения с базовой аутентификацией.
+
[NOTE]
====
На некоторых системах вход с параметром `Username` может приводить ко входу в {dv} под учетной записью пользователя текущей сессии Windows, если вход такого пользователя вообще возможен.
====
+
* `Password` -- пароль пользователя для подключения с базовой аутентификацией.
* `ServerUrl` -- базовый адрес сервера {dv} вида `\http://servername/{dv}`.
* `BaseName` -- имя базы данных, к которой следует подключиться, игнорируя заданную по умолчанию в Консоли настроек.
* `Transport` -- тип транспортного канала для работы с сервисом {dv}:
** `0` -- веб-сервис (HTTP + SOAP).
** `10` -- WCF сервис (HTTP + SOAP).
** `11` -- WCF TCP сервис.
** `12` -- WCF именованный канал (named pipe).
* `ConnectAddress` -- адрес Веб-сервиса {dv} вида `\http://servername/{dv}/StorageServer/StorageServerService.asmx`.
//end::conn-address[]

//tag::disntlm[]
* `DisableNTLM` -- запрещает встроенную аутентификацию:
+
[WARNING]
====
Несколько окон {wincl}а, открытые в одной сессии Windows под разными учетными записями, могут работать нестабильно в связи с особенностями работы Internet Explorer.
====
//end::disntlm[]

//tag::2048[]
* `ShowPanels` -- настройки панелей {wincl}а:
** `0` -- по умолчанию отображается панель иерархии папок и представление.
** `1` -- отображается только иерархия папок.
** `2` -- отображается только представление.
** `3` -- отображается представление и панель предварительного просмотра.
** `4` -- отображается панель иерархии папок, представление и панель предварительного просмотра.
** `256` -- показать {wincl} при открытии карточки (может быть прибавлено к одному из значений `0` -- `4`).
** `512` -- оставлять {wincl} работающим после того, как карточка, открытая по URL, закрывается пользователем (может быть прибавлено к одному из значений `0` -- `4`).
** `1024` -- скрыть панель инструментов {wincl}а (может быть прибавлено к одному из значений `0` -- `4`).
** `2048` -- не показывать заставку при запуске {wincl}а (может быть прибавлено к одному из значений `0` -- `4`).* `ShowPanels` -- настройки панелей {wincl}а:
** `0` -- по умолчанию отображается панель иерархии папок и представление.
** `1` -- отображается только иерархия папок.
** `2` -- отображается только представление.
** `3` -- отображается представление и панель предварительного просмотра.
** `4` -- отображается панель иерархии папок, представление и панель предварительного просмотра.
** `256` -- показать {wincl} при открытии карточки (может быть прибавлено к одному из значений `0` -- `4`).
** `512` -- оставлять {wincl} работающим после того, как карточка, открытая по URL, закрывается пользователем (может быть прибавлено к одному из значений `0` -- `4`).
** `1024` -- скрыть панель инструментов {wincl}а (может быть прибавлено к одному из значений `0` -- `4`).
** `2048` -- не показывать заставку при запуске {wincl}а (может быть прибавлено к одному из значений `0` -- `4`).
//end::2048[]
