//tag::open[]
. Откройте окно xref:settings.adoc["Параметры {wincl}а"], затем выберите набор параметров xref:settings-general.adoc["Основные"].
//end::open[]

//tag::after-refresh[]
Изменение, выполненное обычным пользователем, будет применено сразу же после сохранения карточки. +
Если изменение выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска {wincl}а или обновления xref:interface-navigation-area.adoc#tree[дерева папок].
//end::after-refresh[]

//tag::form[]
.Чтобы ограничить {what}:
. xref:folder-properties.adoc[Откройте] окно свойств папки, затем перейдите на вкладку _{tab}_.
. Чтобы включить ограничение на использование шаблонов, установите флаг `*{flag}*`.
. Сформируйте список {list}: установите флаги напротив допустимых и снимите флаги напротив запрещённых.
+
Чтобы выбрать все записи, воспользуйтесь кнопками *Выделить все* и *Снять все отметки*.
+
. Примените изменения кнопками *Применить* или *ОК*.
//end::form[]

//tag::labels[]
Хранение ярлыков в некоторых папках запрещено. При попытке создать ярлык в такой папке пользователю будет выдано предупреждение.
//end::labels[]

//tag::copy-move[]
[NOTE]
====
Выполнение команды _Копировать карточку_ для _базовых карточек_ приводит к копированию ярлыка. Сама карточка скопирована не будет. Команда _Переместить карточку_ для ярлыков _базовых карточек_ не активна.
====
//end::copy-move[]
